#!/usr/bin/env sh

usage() {
    echo "test <build_dir> [options...]"
}

if [ $# -lt 1 ]; then usage; exit 1; fi

build_dir=$1
shift
if [[ $build_dir == -* ]]; then usage; exit 1; fi

cd "$build_dir" && ninja && ctest --output-on-failure "$@"
