#!/usr/bin/env sh

usage() {
    echo "tidy <build_dir> [options...]"
}

if [ $# -lt 1 ]; then usage; exit 1; fi

build_dir=$1
shift
if [[ $build_dir == -* ]]; then usage; exit 1; fi

find lib -name \*.cpp | xargs clang-tidy -p "$build_dir"
