// stdlib_pack: Pack the Tess standard library into a tlib archive and emit
// a C source file with the raw bytes as a const array, suitable for embedding
// in the compiler binary.
//
// Usage: stdlib_pack <stdlib_dir> <output.c>

#include "alloc.h"
#include "file.h"
#include "platform.h"
#include "str.h"
#include "tlib.h"
#include "types.h"

#include <stdio.h>
#include <string.h>

int main(int argc, char *argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <stdlib_dir> <output.c>\n", argv[0]);
        return 1;
    }

    char const *stdlib_dir  = argv[1];
    char const *output_path = argv[2];

    allocator *alloc = arena_create(default_allocator(), 1024 * 1024);

    // Collect .tl files from stdlib_dir
    c_string_carray files = {.alloc = alloc};
    file_scan_dir_recursive(alloc, stdlib_dir, ".tl", &files);

    if (files.size == 0) {
        fprintf(stderr, "stdlib_pack: no .tl files found in %s\n", stdlib_dir);
        return 1;
    }

    u32 name_count = (u32)files.size;

    // Build tlib entries
    tl_tlib_entry *entries = alloc_calloc(alloc, name_count, sizeof(tl_tlib_entry));

    for (u32 i = 0; i < name_count; i++) {
        char const *filepath = files.v[i];

        char *data     = null;
        u32   data_len = 0;
        file_read(alloc, filepath, &data, &data_len);
        if (!data) {
            fprintf(stderr, "stdlib_pack: failed to read: %s\n", filepath);
            return 1;
        }

        char const *name    = file_basename(filepath);
        entries[i].name     = name;
        entries[i].name_len = (u32)strlen(name);
        entries[i].data     = (byte const *)data;
        entries[i].data_len = data_len;

        fprintf(stderr, "stdlib_pack: packing %s (%u bytes)\n", name, data_len);
    }

    // Write tlib archive to a temp file
    char tlib_path[PLATFORM_PATH_MAX];
    snprintf(tlib_path, sizeof(tlib_path), "%s.tmp.tlib", output_path);

    tl_tlib_metadata meta = {
      .name    = str_init_static("stdlib"),
      .author  = str_empty(),
      .version = str_init_static("1"),
    };

    if (tl_tlib_write(alloc, tlib_path, &meta, entries, name_count)) {
        fprintf(stderr, "stdlib_pack: failed to write tlib archive\n");
        return 1;
    }

    // Read back the tlib file
    char *tlib_data     = null;
    u32   tlib_data_len = 0;
    file_read(alloc, tlib_path, &tlib_data, &tlib_data_len);
    if (!tlib_data) {
        fprintf(stderr, "stdlib_pack: failed to read back tlib archive\n");
        return 1;
    }

    // Remove temp file
    remove(tlib_path);

    // Emit C source
    FILE *out = fopen(output_path, "w");
    if (!out) {
        fprintf(stderr, "stdlib_pack: cannot create output file: %s\n", output_path);
        return 1;
    }

    fprintf(out, "// Auto-generated by stdlib_pack — do not edit\n\n");
    fprintf(out, "unsigned char const tess_stdlib_tlib[] = {\n");

    for (u32 i = 0; i < tlib_data_len; i++) {
        if (i % 16 == 0) fprintf(out, "    ");
        fprintf(out, "0x%02x", (unsigned char)tlib_data[i]);
        if (i + 1 < tlib_data_len) fprintf(out, ",");
        if (i % 16 == 15 || i + 1 == tlib_data_len) fprintf(out, "\n");
    }

    fprintf(out, "};\n\n");
    fprintf(out, "unsigned int const tess_stdlib_tlib_size = %u;\n", tlib_data_len);

    fclose(out);

    fprintf(stderr, "stdlib_pack: generated %s (%u bytes archive, %u files)\n", output_path,
            tlib_data_len, name_count);

    arena_destroy(&alloc);
    return 0;
}
