// stdlib_pack: Pack the Tess standard library into a tpkg archive and emit
// a C source file with the raw bytes as a const array, suitable for embedding
// in the compiler binary.
//
// Usage: stdlib_pack <stdlib_dir> <output.c>

#include "alloc.h"
#include "file.h"
#include "platform.h"
#include "str.h"
#include "tpkg.h"
#include "types.h"

#include <stdio.h>

int main(int argc, char *argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <stdlib_dir> <output.c>\n", argv[0]);
        return 1;
    }

    char const *stdlib_dir  = argv[1];
    char const *output_path = argv[2];

    allocator *alloc = arena_create(default_allocator(), 1024 * 1024);

    // Collect .tl files from stdlib_dir
    c_string_carray files = {.alloc = alloc};
    file_scan_dir_recursive(alloc, stdlib_dir, ".tl", &files);

    if (files.size == 0) {
        fprintf(stderr, "stdlib_pack: no .tl files found in %s\n", stdlib_dir);
        return 1;
    }

    u32 name_count = (u32)files.size;

    // Build tpkg entries
    tl_tpkg_entry *entries = alloc_calloc(alloc, name_count, sizeof(tl_tpkg_entry));

    for (u32 i = 0; i < name_count; i++) {
        char const *filepath = files.v[i];

        char *data     = null;
        u32   data_len = 0;
        file_read(alloc, filepath, &data, &data_len);
        if (!data) {
            fprintf(stderr, "stdlib_pack: failed to read: %s\n", filepath);
            return 1;
        }

        str rel = file_path_relative(alloc, str_init(alloc, stdlib_dir), str_init(alloc, filepath));
        if (str_is_empty(rel)) {
            fprintf(stderr, "stdlib_pack: cannot compute relative path for: %s\n", filepath);
            return 1;
        }
        entries[i].name     = str_cstr_copy(alloc, rel);
        entries[i].name_len = (u32)str_len(rel);
        entries[i].data     = (byte const *)data;
        entries[i].data_len = data_len;

        fprintf(stderr, "stdlib_pack: packing %s (%u bytes)\n", entries[i].name, data_len);
    }

    // Write tpkg archive to a temp file
    char tpkg_path[PLATFORM_PATH_MAX];
    snprintf(tpkg_path, sizeof(tpkg_path), "%s.tmp.tpkg", output_path);

    tl_tpkg_metadata meta = {
      .name    = str_init_static("stdlib"),
      .author  = str_empty(),
      .version = str_init_static("1"),
    };

    if (tl_tpkg_write(alloc, tpkg_path, &meta, entries, name_count)) {
        fprintf(stderr, "stdlib_pack: failed to write tpkg archive\n");
        return 1;
    }

    // Read back the tpkg file
    char *tpkg_data     = null;
    u32   tpkg_data_len = 0;
    file_read(alloc, tpkg_path, &tpkg_data, &tpkg_data_len);
    if (!tpkg_data) {
        fprintf(stderr, "stdlib_pack: failed to read back tpkg archive\n");
        return 1;
    }

    // Remove temp file
    remove(tpkg_path);

    // Emit C source
    FILE *out = fopen(output_path, "w");
    if (!out) {
        fprintf(stderr, "stdlib_pack: cannot create output file: %s\n", output_path);
        return 1;
    }

    fprintf(out, "// Auto-generated by stdlib_pack — do not edit\n\n");
    fprintf(out, "unsigned char const tess_stdlib_tpkg[] = {\n");

    for (u32 i = 0; i < tpkg_data_len; i++) {
        if (i % 16 == 0) fprintf(out, "    ");
        fprintf(out, "0x%02x", (unsigned char)tpkg_data[i]);
        if (i + 1 < tpkg_data_len) fprintf(out, ",");
        if (i % 16 == 15 || i + 1 == tpkg_data_len) fprintf(out, "\n");
    }

    fprintf(out, "};\n\n");
    fprintf(out, "unsigned int const tess_stdlib_tpkg_size = %u;\n", tpkg_data_len);

    fclose(out);

    fprintf(stderr, "stdlib_pack: generated %s (%u bytes archive, %u files)\n", output_path,
            tpkg_data_len, name_count);

    arena_destroy(&alloc);
    return 0;
}
