#include "alloc.h"
#include "array.h"
#include "file.h"
#include "format.h"
#include "hashmap.h"
#include "import_resolver.h"
#include "infer.h"
#include "manifest.h"
#include "parser.h"
#include "source_scanner.h"
#include "str.h"
#include "tlib.h"
#include "transpile.h"
#include "types.h"

#include "platform.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdnoreturn.h>
#include <string.h>

// -- embed externs --
extern char const *embed_prelude_tl;

#include "version.h"

typedef struct {
    allocator        *arena;

    char const       *argv0;
    char const       *out_path;

    c_string_carray   words;

    str               cc;
    str_sized         cflags;
    import_resolver  *resolver;
    str_array         defines;

    tl_source_scanner scanner;

    str               program; // generated by compile()
    str               header;  // generated by compile() for c_export headers

    int               no_line_directive;
    int               no_standard_includes;
    int               verbose;
    int               verbose_ast;
    int               verbose_parse;
    int               report_time;  // --time option
    int               report_stats; // --stats option
    int               help;
    int               optimize;

    int               in_place;
    int               unpack_list; // --list option for unpack command

    int               is_library;
    int               is_executable;

    // Temp directories created during package extraction (cleaned up in state_deinit)
    c_string_carray temp_dirs;

    // Compilation statistics (populated when report_stats is set)
    struct {
        double               parse_time_ms;
        size_t               parse_peak_mem;
        size_t               parse_final_mem;
        double               infer_time_ms;
        size_t               infer_peak_mem;
        size_t               infer_final_mem;
        double               transpile_time_ms;
        size_t               transpile_peak_mem;
        size_t               transpile_final_mem;
        double               cc_time_ms;
        size_t               cc_input_size; // Size of C source passed to compiler

        tl_infer_phase_stats infer_phases;
        tl_infer_counters    infer_counters;
    } stats;
} state;

noreturn void usage(int status, char const *argv0) {
    char const *progname = file_basename(argv0);

    printf("Usage: %s [-hv] <command> [-o outpath] [path1 path2 ... pathn] \n", progname);
    puts("Commands:\n");
    printf("    c                      transpile input files to C\n");
    printf("    exe                    compile and create executable (-o required)\n");
    printf("    fmt                    format source file (reads stdin if no file given)\n");
    printf("    init                   create a package.tl in the current directory\n");
    printf("    lib                    compile and create shared library (-o required)\n");
    printf("    lib-emit-c             transpile input files to C as library source code\n");
    printf("    pack                   create .tlib archive from source files (-o required, reads "
           "package.tl)\n");
    printf("    validate               validate source files against package.tl\n");
    printf(
      "    unpack                 extract .tlib archive (-o for output dir (default .), --list to list)\n");
    printf("\nOptions:\n");
    printf("    -h                     print usage and exit\n");
    printf("    -V, --version          print version and exit\n");
    printf("    -D <symbol>            define <symbol> for conditional compilation\n");
    printf("    -I <path>              add user include path for \"...\" imports. Multiple ok.\n");
    printf("    -S <path>              add standard library path for <...> imports. Multiple ok.\n");
    printf("    -o <path>              write output to path instead of stdout\n");
    printf("    -i, --in-place         overwrite file in place (fmt command only)\n");
    printf("    --list                 list archive contents without extracting (unpack only)\n");
    printf("    -O                     optimize C build (with -O2). Use CFLAGS for other flags.\n");
    printf("    -v                     verbose logging\n");
    printf("    --no-line-directive    suppress output of #line directives in C file\n");
    printf("    --no-standard-includes do not add default standard library paths\n");
    printf("    --stats                report memory and time statistics per phase\n");
    printf("    --time                 report elapsed time of compilation process\n");
    printf("    --verbose-ast          produce full recursive ast output when -v is set\n");
    printf("    --verbose-parse        produce large amount of parse progress output\n");
    exit(status);
}

noreturn void version() {
    printf("%s\n", TESS_VERSION);
    exit(0);
}

void state_init(state *self) {
    alloc_zero(self);
    self->arena    = arena_create(default_allocator(), 1024 * 1024);
    self->argv0    = null;
    self->out_path = null;
    self->words    = (c_string_carray){.alloc = self->arena};
    array_reserve(self->words, 32);
    self->cc                   = str_empty();
    self->cflags               = (str_sized){0};
    self->resolver             = import_resolver_create(self->arena);
    self->defines              = (str_array){.alloc = self->arena};
    self->scanner              = tl_source_scanner_create(self->arena, self->resolver);
    self->program              = str_empty();
    self->verbose              = 0;
    self->verbose_ast          = 0;
    self->verbose_parse        = 0;
    self->report_time          = 0;
    self->report_stats         = 0;
    self->no_line_directive    = 0;
    self->no_standard_includes = 0;
    self->help                 = 0;
    self->optimize             = 0;
    self->in_place             = 0;
    self->is_library           = 0;
    self->is_executable        = 0;
    self->temp_dirs            = (c_string_carray){.alloc = self->arena};
}

static void state_track_temp_dir(state *self, char const *path) {
    str         s    = str_init(self->arena, path);
    char const *copy = str_cstr(&s);
    array_push(self->temp_dirs, copy);
}

void state_deinit(state *self) {
    forall(i, self->temp_dirs) {
        platform_temp_path_delete_recursive(self->temp_dirs.v[i]);
    }

    arena_destroy(&self->arena);

    alloc_invalidate(self);
}

void state_gather_single_options(state *self, char *str) {
    u32 len = (u32)strlen(str);
    for (u32 i = 1; i < len; ++i) {
        switch (str[i]) {
        case 'h': self->help = 1; break;
        case 'v': self->verbose = 1; break;
        case 'V': version(); break;
        case 'i': self->in_place = 1; break;
        case 'O': self->optimize = 1; break;
        default:  usage(1, self->argv0); break;
        }
    }
}

void state_gather_long_option(state *self, char *str) {
    if (0 == strcmp("--version", str)) version();
    else if (0 == strcmp("--verbose-ast", str)) self->verbose_ast = 1;
    else if (0 == strcmp("--verbose-parse", str)) self->verbose_parse = 1;
    else if (0 == strcmp("--no-line-directive", str)) self->no_line_directive = 1;
    else if (0 == strcmp("--no-standard-includes", str)) self->no_standard_includes = 1;
    else if (0 == strcmp("--in-place", str)) self->in_place = 1;
    else if (0 == strcmp("--list", str)) self->unpack_list = 1;
    else if (0 == strcmp("--time", str)) self->report_time = 1;
    else if (0 == strcmp("--stats", str)) self->report_stats = 1;
    else if (0 == strcmp("--", str)) /* ignore */
        ;
    else usage(1, self->argv0);
}

void state_gather_options(state *self, int argc, char *argv[]) {

    self->argv0 = argv[0];

    // Flags -o, -I, -D accept values with or without a space (e.g. -ofoo or -o foo).
    for (int i = 1; i < argc; ++i) {
        if ('-' == argv[i][0]) {

            if (0 == strncmp("-o", argv[i], 2)) {
                self->out_path = argv[i][2] ? argv[i] + 2 : argv[++i];
                continue;
            } else if (0 == strncmp("-I", argv[i], 2)) {
                char const *val  = argv[i][2] ? argv[i] + 2 : argv[++i];
                str         path = str_init(self->arena, val);
                import_resolver_add_user_path(self->resolver, path);
            } else if (0 == strncmp("-S", argv[i], 2)) {
                char const *val  = argv[i][2] ? argv[i] + 2 : argv[++i];
                str         path = str_init(self->arena, val);
                import_resolver_add_standard_path(self->resolver, path);
            } else if (0 == strncmp("-D", argv[i], 2)) {
                char const *sym    = argv[i][2] ? argv[i] + 2 : argv[++i];
                str         define = str_init(self->arena, sym);
                array_push(self->defines, define);
            } else if (0 == strncmp("--", argv[i], 2)) {
                state_gather_long_option(self, argv[i]);
            } else {
                state_gather_single_options(self, argv[i]);
            }

        } else {
            array_push(self->words, argv[i]);
        }
    }
}

void eval_print(char *in) {
    printf("you said: '%s'\n", in);
}

static void scan_directives(state *self, str file_path, char_csized input, str_array *imports) {
    if (tl_source_scanner_scan(&self->scanner, file_path, input, imports)) {
        exit(1);
    }
}

static void print_import_paths(state *self) {
    import_resolver_print_paths(self->resolver);
}

static void add_standard_include_paths(state *self, char const *cwd) {
    char exe_buf[4096];
    span exe_span = {.buf = exe_buf, .len = sizeof(exe_buf)};

    // 1. Add <exe_dir>/../lib/tess/std (for installed tess)
    if (file_exe_directory(exe_span)) {
        str exe_dir       = str_init(self->arena, exe_buf);
        str installed_std = str_cat(self->arena, exe_dir, S("/../lib/tess/std"));
        import_resolver_add_standard_path(self->resolver, installed_std);

        // 1b. add <exe_dir>/src/tl/std (for development builds)
        str development_std = str_cat(self->arena, exe_dir, S("/src/tl/std"));
        import_resolver_add_standard_path(self->resolver, development_std);
    }

    // 2. Add <cwd>/src/tl/std (for development builds)
    str cwd_std = str_cat(self->arena, str_init_static(cwd), S("/src/tl/std"));
    import_resolver_add_standard_path(self->resolver, cwd_std);
}

// Resolve an import path using the import resolver
// Returns empty string on error (error already printed)
static str resolve_import(state *self, str import_path, str importing_file) {
    import_result result = import_resolver_resolve(self->resolver, import_path, importing_file);

    if (str_is_empty(result.canonical_path)) {
        exit(1); // Error already printed by resolver
    }

    return result.canonical_path;
}

static void collect_imports_from_import(state *self, str import_path, str importing_file,
                                        str_array *resolved_paths) {
    if (str_is_empty(import_path)) return;

    // Resolve the import path
    import_result result = import_resolver_resolve(self->resolver, import_path, importing_file);

    if (str_is_empty(result.canonical_path)) {
        exit(1); // Error already printed by resolver
    }

    // Skip if already imported (duplicate detection)
    if (result.is_duplicate) {
        return;
    }

    // Check for circular imports
    if (import_resolver_begin_import(self->resolver, result.canonical_path)) {
        fprintf(stderr, "error: circular import detected: %s\n", str_cstr(&result.canonical_path));
        exit(1);
    }

    // Mark as imported
    import_resolver_mark_imported(self->resolver, result.canonical_path);

    // Read file and scan for directives
    char *data;
    u32   size;
    file_read(self->arena, str_cstr(&result.canonical_path), &data, &size);

    str_array file_imports = {.alloc = self->arena};
    scan_directives(self, result.canonical_path, (char_csized){.size = size, .v = data}, &file_imports);

    // Recursively collect imports from this file
    forall(i, file_imports) {
        collect_imports_from_import(self, file_imports.v[i], result.canonical_path, resolved_paths);
    }

    // Add to output after processing dependencies (topological order)
    array_push(*resolved_paths, result.canonical_path);

    // Mark import as complete
    import_resolver_end_import(self->resolver, result.canonical_path);
}

static void scan_file_directives(state *self, str path, str_array *resolved_paths) {
    char *data;
    u32   size;

    file_read(self->arena, str_cstr(&path), &data, &size);

    str_array file_imports = {.alloc = self->arena};
    scan_directives(self, path, (char_csized){.size = size, .v = data}, &file_imports);

    forall(i, file_imports) {
        collect_imports_from_import(self, file_imports.v[i], path, resolved_paths);
    }
}

// Find a .tlib file for a dependency.
// If dep->path is non-empty (3-arg depend()), use it directly.
// Otherwise, search depend_path() directories for <name>.tlib.
static str resolve_tlib_path(state *self, tl_package_dep const *dep, tl_package_info const *info) {
    if (!str_is_empty(dep->path)) {
        return dep->path;
    }

    str tlib_name = str_cat_c(self->arena, dep->name, ".tlib");
    for (u32 i = 0; i < info->depend_path_count; i++) {
        str candidate = str_cat_3(self->arena, info->depend_paths[i], S("/"), tlib_name);
        if (file_exists(candidate)) {
            return candidate;
        }
    }

    return str_empty();
}

// Parse "Name=Version" dependency string from archive metadata into components.
// Returns 0 on success, 1 on malformed input.
static int parse_dep_string(allocator *alloc, str dep_str, str *out_name, str *out_version) {
    char const *s  = str_cstr(&dep_str);
    char const *eq = strchr(s, '=');
    if (!eq || eq == s || !eq[1]) return 1;
    *out_name    = str_init_n(alloc, s, (size_t)(eq - s));
    *out_version = str_init_n(alloc, eq + 1, str_len(dep_str) - (size_t)(eq - s) - 1);
    return 0;
}

// Info about which package exported a module (for duplicate detection).
typedef struct {
    str pkg_name;
    str tlib_path;
} module_pkg_info;

// Context for recursive dependency resolution.
typedef struct {
    hashmap  *loaded;        // name -> version (str->str map) for dedup and conflict detection
    str_array stack;         // package names currently being resolved (cycle detection)
    hashmap  *module_owners; // module_name (str) -> module_pkg_info for duplicate detection
} dep_resolve_ctx;

// Check for duplicate module names across packages after extraction.
// Warns (but does not fail) if two packages export the same module.
static void check_duplicate_modules(tl_tlib_metadata *meta, str tlib_path, dep_resolve_ctx *ctx) {
    for (u16 i = 0; i < meta->module_count; i++) {
        str mod = meta->modules[i];
        if (str_map_contains(ctx->module_owners, mod)) {
            module_pkg_info *existing = str_map_get(ctx->module_owners, mod);
            fprintf(stderr,
                    "warning: module '%s' exported by package '%s' (%s)"
                    " was already exported by package '%s' (%s)\n",
                    str_cstr(&mod), str_cstr(&meta->name), str_cstr(&tlib_path),
                    str_cstr(&existing->pkg_name), str_cstr(&existing->tlib_path));
        } else {
            module_pkg_info info = {.pkg_name = meta->name, .tlib_path = tlib_path};
            str_map_set(&ctx->module_owners, mod, &info);
        }
    }
}

// Recursively resolve a single dependency and its transitive deps.
// Uses consumer's depend_path directories for transitive resolution.
static int resolve_dep_recursive(state *self, str dep_name, str dep_version,
                                 tl_package_info const *consumer_info, dep_resolve_ctx *ctx,
                                 str_array *out_pkg_files) {
    // Check for cycle: is this package already on the resolution stack?
    for (u32 i = 0; i < ctx->stack.size; i++) {
        if (str_eq(ctx->stack.v[i], dep_name)) {
            fprintf(stderr, "error: circular dependency: ");
            for (u32 j = i; j < ctx->stack.size; j++) {
                fprintf(stderr, "%s -> ", str_cstr(&ctx->stack.v[j]));
            }
            fprintf(stderr, "%s\n", str_cstr(&dep_name));
            return 1;
        }
    }

    // Check if already loaded
    if (str_map_contains(ctx->loaded, dep_name)) {
        str *loaded_version = str_map_get(ctx->loaded, dep_name);
        if (!str_eq(*loaded_version, dep_version)) {
            fprintf(stderr, "error: version conflict for package '%s': requires both '%s' and '%s'\n",
                    str_cstr(&dep_name), str_cstr(loaded_version), str_cstr(&dep_version));
            return 1;
        }
        return 0; // already loaded with matching version
    }

    // Resolve .tlib path
    tl_package_dep synth_dep = {.name = dep_name, .version = dep_version, .path = str_empty()};
    str            tlib_path = resolve_tlib_path(self, &synth_dep, consumer_info);
    if (str_is_empty(tlib_path)) {
        fprintf(stderr, "error: package '%s=%s' not found", str_cstr(&dep_name), str_cstr(&dep_version));
        if (ctx->stack.size > 0) {
            fprintf(stderr, " (required by '%s')", str_cstr(&ctx->stack.v[ctx->stack.size - 1]));
        }
        if (consumer_info->depend_path_count > 0) {
            fprintf(stderr, "; searched:");
            for (u32 j = 0; j < consumer_info->depend_path_count; j++) {
                fprintf(stderr, " %s", str_cstr(&consumer_info->depend_paths[j]));
            }
        }
        fprintf(stderr, "\n");
        return 1;
    }

    // Read archive
    tl_tlib_archive archive;
    if (tl_tlib_read(self->arena, str_cstr(&tlib_path), &archive)) {
        fprintf(stderr, "error: failed to read package '%s' from '%s'\n", str_cstr(&dep_name),
                str_cstr(&tlib_path));
        return 1;
    }

    // Verify version
    if (!str_eq(archive.metadata.version, dep_version)) {
        fprintf(stderr, "error: package '%s' version mismatch: expected '%s', found '%s' in '%s'\n",
                str_cstr(&dep_name), str_cstr(&dep_version), str_cstr(&archive.metadata.version),
                str_cstr(&tlib_path));
        return 1;
    }

    // Push onto resolution stack
    array_push(ctx->stack, dep_name);

    // Recursively resolve transitive dependencies
    for (u16 i = 0; i < archive.metadata.depends_count; i++) {
        str trans_name    = str_empty();
        str trans_version = str_empty();
        if (parse_dep_string(self->arena, archive.metadata.depends[i], &trans_name, &trans_version)) {
            fprintf(stderr, "error: malformed dependency string '%s' in package '%s'\n",
                    str_cstr(&archive.metadata.depends[i]), str_cstr(&dep_name));
            return 1;
        }
        if (resolve_dep_recursive(self, trans_name, trans_version, consumer_info, ctx, out_pkg_files)) {
            return 1;
        }
    }

    // Pop from resolution stack
    ctx->stack.size--;

    // Mark as loaded
    str_map_set(&ctx->loaded, dep_name, &dep_version);

    // Extract to temp directory
    platform_temp_path tmppath;
    if (platform_temp_path_create(&tmppath, "tess-pkg-")) {
        fprintf(stderr, "error: failed to create temp directory for package '%s'\n", str_cstr(&dep_name));
        return 1;
    }
    state_track_temp_dir(self, tmppath.path);

    if (tl_tlib_extract(self->arena, &archive, tmppath.path, out_pkg_files)) {
        fprintf(stderr, "error: failed to extract package '%s'\n", str_cstr(&dep_name));
        return 1;
    }

    check_duplicate_modules(&archive.metadata, tlib_path, ctx);

    if (self->verbose) {
        fprintf(stderr, "Loaded package: %s=%s from %s (%u files to %s)\n", str_cstr(&dep_name),
                str_cstr(&dep_version), str_cstr(&tlib_path), archive.entries_count, tmppath.path);
    }

    return 0;
}

// Load package dependencies from package.tl in CWD.
// Resolves direct and transitive dependencies recursively.
// Extracts .tlib archives to temp directories and returns extracted file paths.
// Returns 0 on success (including no package.tl), 1 on error.
static int load_package_deps(state *self, str_array *out_pkg_files) {
    str pkg_path = str_init_static("package.tl");
    if (!file_exists(pkg_path)) {
        return 0;
    }

    tl_package pkg = {0};
    if (tl_package_parse_file(self->arena, "package.tl", &pkg)) {
        return 1;
    }

    if (pkg.dep_count == 0) {
        return 0;
    }

    dep_resolve_ctx ctx = {
      .loaded        = map_new(self->arena, str, str, 8),
      .stack         = {.alloc = self->arena},
      .module_owners = map_new(self->arena, str, module_pkg_info, 16),
    };

    for (u32 i = 0; i < pkg.dep_count; i++) {
        tl_package_dep *dep = &pkg.deps[i];

        // Direct deps may have explicit paths; use resolve_tlib_path with the original dep
        str tlib_path = resolve_tlib_path(self, dep, &pkg.info);
        if (str_is_empty(tlib_path)) {
            fprintf(stderr, "error: package '%s=%s' not found", str_cstr(&dep->name),
                    str_cstr(&dep->version));
            if (pkg.info.depend_path_count > 0) {
                fprintf(stderr, "; searched:");
                for (u32 j = 0; j < pkg.info.depend_path_count; j++) {
                    fprintf(stderr, " %s", str_cstr(&pkg.info.depend_paths[j]));
                }
            }
            fprintf(stderr, "\n");
            return 1;
        }

        // Check if already loaded (handles diamond deps where a direct dep
        // was already loaded as a transitive dep of a previous direct dep)
        if (str_map_contains(ctx.loaded, dep->name)) {
            str *loaded_version = str_map_get(ctx.loaded, dep->name);
            if (!str_eq(*loaded_version, dep->version)) {
                fprintf(stderr, "error: version conflict for package '%s': requires both '%s' and '%s'\n",
                        str_cstr(&dep->name), str_cstr(loaded_version), str_cstr(&dep->version));
                return 1;
            }
            continue; // already loaded with matching version
        }

        // Read archive
        tl_tlib_archive archive;
        if (tl_tlib_read(self->arena, str_cstr(&tlib_path), &archive)) {
            fprintf(stderr, "error: failed to read package '%s' from '%s'\n", str_cstr(&dep->name),
                    str_cstr(&tlib_path));
            return 1;
        }

        // Verify version
        if (!str_eq(archive.metadata.version, dep->version)) {
            fprintf(stderr, "error: package '%s' version mismatch: expected '%s', found '%s' in '%s'\n",
                    str_cstr(&dep->name), str_cstr(&dep->version), str_cstr(&archive.metadata.version),
                    str_cstr(&tlib_path));
            return 1;
        }

        // Push onto resolution stack
        array_push(ctx.stack, dep->name);

        // Recursively resolve transitive dependencies
        for (u16 j = 0; j < archive.metadata.depends_count; j++) {
            str trans_name    = str_empty();
            str trans_version = str_empty();
            if (parse_dep_string(self->arena, archive.metadata.depends[j], &trans_name, &trans_version)) {
                fprintf(stderr, "error: malformed dependency string '%s' in package '%s'\n",
                        str_cstr(&archive.metadata.depends[j]), str_cstr(&dep->name));
                return 1;
            }
            if (resolve_dep_recursive(self, trans_name, trans_version, &pkg.info, &ctx, out_pkg_files)) {
                return 1;
            }
        }

        // Pop from resolution stack
        ctx.stack.size--;

        // Mark as loaded
        str_map_set(&ctx.loaded, dep->name, &dep->version);

        // Extract to temp directory
        platform_temp_path tmppath;
        if (platform_temp_path_create(&tmppath, "tess-pkg-")) {
            fprintf(stderr, "error: failed to create temp directory for package '%s'\n",
                    str_cstr(&dep->name));
            return 1;
        }
        state_track_temp_dir(self, tmppath.path);

        if (tl_tlib_extract(self->arena, &archive, tmppath.path, out_pkg_files)) {
            fprintf(stderr, "error: failed to extract package '%s'\n", str_cstr(&dep->name));
            return 1;
        }

        check_duplicate_modules(&archive.metadata, tlib_path, &ctx);

        if (self->verbose) {
            fprintf(stderr, "Loaded package: %s=%s from %s (%u files to %s)\n", str_cstr(&dep->name),
                    str_cstr(&dep->version), str_cstr(&tlib_path), archive.entries_count, tmppath.path);
        }
    }

    return 0;
}

static str_sized files_in_order(state *self, c_string_csized files, str_sized pkg_files) {
    // Scan package files for directives first (discovers #module names, resolves imports)
    str_array resolved_paths = {.alloc = self->arena};
    array_reserve(resolved_paths, 32);

    str_array result = {.alloc = self->arena};
    array_reserve(result, resolved_paths.size + pkg_files.size + files.size + 1);

    // Resolve builtin.tl (always first)
    str builtin = resolve_import(self, S("<builtin.tl>"), str_empty());
    if (str_is_empty(builtin)) {
        fprintf(stderr, "error: failed to find 'builtin.tl'\n");
        print_import_paths(self);
        exit(1);
    }
    scan_file_directives(self, builtin, &resolved_paths);

    // push builtin's dependencies first
    array_copy(result, resolved_paths);

    // push builtin
    array_push(result, builtin);

    // reset resolved_paths after processing builtin
    resolved_paths.size = 0;

    // process package files
    forall(i, pkg_files) {
        scan_file_directives(self, pkg_files.v[i], &resolved_paths);
    }

    // Collect all imports from user files
    forall(i, files) {
        scan_file_directives(self, str_init_static(files.v[i]), &resolved_paths);
    }

    // Add resolved imports (already in correct dependency order)
    forall(i, resolved_paths) {
        array_push(result, resolved_paths.v[i]);
    }

    // Add package files not already in imports list
    forall(i, pkg_files) {
        if (!import_resolver_is_imported(self->resolver, pkg_files.v[i])) {
            array_push(result, pkg_files.v[i]);
        }
    }

    // Add user files
    forall(i, files) {
        str file = str_init(self->arena, files.v[i]);
        array_push(result, file);
    }

    return (str_sized)array_sized(result);
}

//

static void output_program(state *self) {
    if (self->out_path) {
        FILE *f = fopen(self->out_path, "wb");
        if (!f) fatal("could not open output file: '%s'", self->out_path);

        fprintf(f, "%.*s", str_ilen(self->program), str_buf(&self->program));

        fclose(f);
    } else {
        printf("%.*s", str_ilen(self->program), str_buf(&self->program));
    }
}

static void get_c_compiler(state *self) {
    char const *CC = getenv("CC");
    if (CC) {
        self->cc = str_init(self->arena, CC);
    }
#ifdef MOS_WINDOWS
    else if (platform_command_exists("cl"))
        self->cc = str_init(self->arena, "cl");
    else if (platform_command_exists("clang")) self->cc = str_init(self->arena, "clang");
    else if (platform_command_exists("gcc")) self->cc = str_init(self->arena, "gcc");
#else
    else if (platform_command_exists("cc"))
        self->cc = str_init(self->arena, "cc");
    else if (platform_command_exists("gcc")) self->cc = str_init(self->arena, "gcc");
    else if (platform_command_exists("clang")) self->cc = str_init(self->arena, "clang");
#endif
    else self->cc = str_empty();

    char const *CFLAGS = getenv("CFLAGS");

    if (CFLAGS) {
        str       cflags = str_init(self->arena, CFLAGS);
        str_array arr    = {.alloc = self->arena};
        str_parse_words(cflags, &arr);
        self->cflags = (str_sized)array_sized(arr);
    } else {
        self->cflags = (str_sized){0};
    }
}

// -- stats formatting helpers --

static void format_memory(char *buf, size_t sz, size_t bytes) {
    if (bytes < 1024) snprintf(buf, sz, "%zu B", bytes);
    else if (bytes < 1024 * 1024) snprintf(buf, sz, "%.1f KB", bytes / 1024.0);
    else snprintf(buf, sz, "%.2f MB", bytes / (1024.0 * 1024.0));
}

static void print_stats_header(void) {
    fprintf(stderr, "\n=== Compilation Statistics ===\n\n");
    fprintf(stderr, "%-20s %12s %12s %12s\n", "Phase", "Time (ms)", "Peak Mem", "Final Mem");
    fprintf(stderr, "%-20s %12s %12s %12s\n", "--------------------", "------------", "------------",
            "------------");
}

static void print_stats_row(char const *phase, double time_ms, size_t peak_mem, size_t final_mem) {
    char peak_buf[32], final_buf[32];
    format_memory(peak_buf, sizeof peak_buf, peak_mem);
    format_memory(final_buf, sizeof final_buf, final_mem);
    fprintf(stderr, "%-20s %12.3f %12s %12s\n", phase, time_ms, peak_buf, final_buf);
}

static void print_stats_row_no_mem(char const *phase, double time_ms, size_t input_size) {
    char size_buf[32];
    format_memory(size_buf, sizeof size_buf, input_size);
    fprintf(stderr, "%-20s %12.3f %12s %12s\n", phase, time_ms, "-", size_buf);
}

static void print_stats_footer(double total_ms, size_t total_peak) {
    char peak_buf[32];
    format_memory(peak_buf, sizeof peak_buf, total_peak);
    fprintf(stderr, "%-20s %12s %12s %12s\n", "--------------------", "------------", "------------",
            "------------");
    fprintf(stderr, "%-20s %12.3f %12s\n", "TOTAL", total_ms, peak_buf);
    fprintf(stderr, "\n");
}

int compile(state *self) {
    if (self->words.size < 2) usage(1, self->argv0);

    int error = 0;

    // Stats collection
    hires_timer phase_timer;
    hires_timer_init(&phase_timer);

    c_string_csized paths = {.v = &self->words.v[1], .size = self->words.size - 1};

    // Load package dependencies (if package.tl exists with depend() declarations)
    str_array pkg_files = {.alloc = self->arena};
    if (load_package_deps(self, &pkg_files)) return 1;

    tl_infer_opts infer_opts  = {.is_library = self->is_library};
    tl_infer     *infer       = tl_infer_create(self->arena, &infer_opts);

    parser_opts   parser_opts = {
        .registry = tl_infer_get_registry(infer),
        .files    = files_in_order(self, paths, (str_sized)array_sized(pkg_files)),
        .prelude  = embed_prelude_tl,
        .defines  = self->defines,
      // The parser validates nested modules (#module Foo.Bar) by checking that the
      // parent (Foo) exists. Without this, cross-file nested modules fail when import
      // resolution orders the child before the parent (the parser hasn't seen Foo yet).
      // The scanner has already discovered all modules, so we pass its map here.
        .known_modules = self->scanner.modules_seen,
    };

    // === PARSING PHASE ===
    hires_timer_start(&phase_timer);

    parser *parser = parser_create(self->arena, &parser_opts);
    if (!parser) fatal("could not create parser");
    parser_set_verbose(parser, self->verbose_parse);

    allocator     *nodes_alloc = arena_create(self->arena, 64 * 1024);
    ast_node_array nodes       = {.alloc = nodes_alloc};

    // parser first pass
    if (parser_parse_all_symbols(parser)) {
        parser_report_errors(parser);
        ++error;
        goto cleanup_parser;
    }

    hashmap *syms = parser_take_module_symbols(parser);
    parser_destroy(&parser);

    // parser second pass
    parser = parser_create(self->arena, &parser_opts);

    parser_set_module_symbols(parser, syms);

    if (self->verbose_parse) {
        if (parser_parse_all_verbose(parser, &nodes)) {
            parser_report_errors(parser);
            ++error;
            goto cleanup_parser;
        }
    } else {
        if (parser_parse_all(parser, &nodes)) {
            parser_report_errors(parser);
            ++error;
            goto cleanup_parser;
        }
    }

    hires_timer_stop(&phase_timer);
    if (self->report_stats) {
        self->stats.parse_time_ms = hires_timer_elapsed_sec(&phase_timer) * 1000.0;
        arena_stats ast_stats, token_stats;
        parser_get_arena_stats(parser, &ast_stats, &token_stats);
        self->stats.parse_peak_mem  = ast_stats.peak_allocated + token_stats.peak_allocated;
        self->stats.parse_final_mem = ast_stats.allocated + token_stats.allocated;
    }

    // === TYPE INFERENCE PHASE ===
    hires_timer_start(&phase_timer);

    tl_infer_result infer_result = {0};
    tl_infer_set_verbose(infer, self->verbose);
    tl_infer_set_verbose_ast(infer, self->verbose_ast);
    if (self->report_stats) tl_infer_set_report_stats(infer, 1);
    if (tl_infer_run(infer, (ast_node_sized)sized_all(nodes), &infer_result)) {
        tl_infer_report_errors(infer);
        error++;
        goto cleanup_ti;
    }

    hires_timer_stop(&phase_timer);
    if (self->report_stats) {
        self->stats.infer_time_ms = hires_timer_elapsed_sec(&phase_timer) * 1000.0;
        arena_stats infer_arena_stats;
        tl_infer_get_arena_stats(infer, &infer_arena_stats);
        self->stats.infer_peak_mem  = infer_arena_stats.peak_allocated;
        self->stats.infer_final_mem = infer_arena_stats.allocated;

        self->stats.infer_phases    = *tl_infer_get_phase_stats(infer);
        self->stats.infer_counters  = *tl_infer_get_counters(infer);
    }

    // === TRANSPILATION PHASE ===
    hires_timer_start(&phase_timer);

    // Derive library name from output path for namespaced tl_init
    str lib_name = str_empty();
    if (self->is_library && self->out_path) {
        char const *base = strrchr(self->out_path, '/');
#ifdef MOS_WINDOWS
        {
            char const *bslash = strrchr(self->out_path, '\\');
            if (bslash && (!base || bslash > base)) base = bslash;
        }
#endif
        base = base ? base + 1 : self->out_path;
        // Strip "lib" prefix if present (libfoo.so -> foo)
        if (0 == strncmp(base, "lib", 3)) base += 3;
        char const *dot = strrchr(base, '.');
        u32         len = dot ? (u32)(dot - base) : (u32)strlen(base);
        if (len > 0) lib_name = str_init_n(self->arena, base, len);
    }

    transpile_opts transpile_opts = {
      .infer_result      = infer_result,
      .is_library        = self->is_library,
      .no_line_directive = self->no_line_directive,
      .verbose           = self->verbose,
      .lib_name          = lib_name,
    };
    transpile *transpile = transpile_create(self->arena, &transpile_opts);

    str_build  program_build;
    if (transpile_compile(transpile, &program_build)) goto cleanup_tp;

    hires_timer_stop(&phase_timer);
    if (self->report_stats) {
        self->stats.transpile_time_ms = hires_timer_elapsed_sec(&phase_timer) * 1000.0;
        arena_stats tp_arena_stats;
        transpile_get_arena_stats(transpile, &tp_arena_stats);
        self->stats.transpile_peak_mem  = tp_arena_stats.peak_allocated;
        self->stats.transpile_final_mem = tp_arena_stats.allocated;
    }

    str program = str_build_finish(&program_build);

    if (self->is_library && self->out_path) {
        // Generate c_export header if there are any exported functions
        str_build header_build = {0};
        // Derive guard name from header filename (output path with .h extension)
        char const *basename = strrchr(self->out_path, '/');
        basename             = basename ? basename + 1 : self->out_path;
        char guard[256];
        {
            u32         gi  = 0;
            char const *dot = strrchr(basename, '.');
            u32         len = dot ? (u32)(dot - basename) : (u32)strlen(basename);
            for (u32 k = 0; k < len && gi < sizeof guard - 3; k++) {
                char c = basename[k];
                if (('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || ('0' <= c && c <= '9'))
                    guard[gi++] = (char)((c >= 'a' && c <= 'z') ? c - 32 : c);
                else guard[gi++] = '_';
            }
            guard[gi++] = '_';
            guard[gi++] = 'H';
            guard[gi]   = '\0';
        }
        str guard_str = str_init(self->arena, guard);
        if (transpile_generate_header(transpile, &header_build, guard_str)) {
            self->header = str_build_finish(&header_build);
        }
    }

    if (self->is_executable || self->is_library) {
        // Save program and return to caller
        self->program = program;
        goto done;
    } else {
        // output C source code
        self->program = program;
        output_program(self);
    }

    str_deinit(self->arena, &program);

done:
    // is_executable || is_library: Caller will take over program
cleanup_tp:
    transpile_destroy(self->arena, &transpile);

cleanup_ti:
    tl_infer_destroy(self->arena, &infer);

cleanup_parser:
    parser_destroy(&parser);
    array_free(nodes);
    arena_destroy(&nodes_alloc);
    return error;
}

#ifdef MOS_WINDOWS
static int is_msvc_compiler(state *self) {
    char const *cc = str_cstr(&self->cc);
    return (0 == strcmp(cc, "cl") || 0 == strcmp(cc, "cl.exe"));
}
#endif

// Build argv array for gcc/clang compiler invocation
// extra_flags: array of additional flags (e.g., "-shared", "-fPIC")
// extra_flags_count: number of additional flags
// use_temp_file: if non-null, use this temp file path; otherwise read from stdin
static c_string_array build_gcc_argv(state *self, char const **extra_flags, int extra_flags_count,
                                     char const *temp_file) {
    char const    *cc   = str_cstr(&self->cc);

    c_string_array argv = {.alloc = self->arena};
    array_reserve(argv, self->cflags.size + extra_flags_count + 16);
    array_push(argv, cc);

    // clang-format off
    { char const *_t = "-o"; array_push(argv, _t); }
    array_push(argv, self->out_path);
    // clang-format on

    if (self->optimize) {
        char const *_t = "-O2";
        array_push(argv, _t);
    }

    forall(i, self->cflags) {
        char const *cstr = str_cstr(&self->cflags.v[i]);
        array_push(argv, cstr);
    }

    // clang-format off
    { char const *_t = "-std=c11"; array_push(argv, _t); }
    { char const *_t = "-Wno-format-security"; array_push(argv, _t); }
    // clang-format on

    for (int i = 0; i < extra_flags_count; i++) {
        array_push(argv, extra_flags[i]);
    }

    if (temp_file) {
        array_push(argv, temp_file);
    } else {
        // clang-format off
        { char const *_t = "-x"; array_push(argv, _t); }
        { char const *_t = "c"; array_push(argv, _t); }
        { char const *_t = "-"; array_push(argv, _t); }
        // clang-format on
    }

    {
        char const *_t = null;
        array_push(argv, _t);
    }

    return argv;
}

#ifdef MOS_WINDOWS

// Build argv array for MSVC compiler invocation
// msvc_extra_flags: array of additional flags (e.g., "/LD")
// msvc_extra_flags_count: number of additional flags
// c_file: path to C source file
// obj_file: path for object file output
static c_string_array build_msvc_argv(state *self, char const **msvc_extra_flags,
                                      int msvc_extra_flags_count, char const *c_file,
                                      char const *obj_file) {
    c_string_array argv = {.alloc = self->arena};
    array_reserve(argv, self->cflags.size + msvc_extra_flags_count + 16);

    char const *cc = str_cstr(&self->cc);
    array_push(argv, cc);

    {
        char const *_t = "/nologo";
        array_push(argv, _t);
    }

    for (int i = 0; i < msvc_extra_flags_count; i++) {
        array_push(argv, msvc_extra_flags[i]);
    }

    if (self->optimize) {
        char const *_t = "/O2";
        array_push(argv, _t);
    }

    forall(i, self->cflags) {
        char const *cstr = str_cstr(&self->cflags.v[i]);
        array_push(argv, cstr);
    }

    // Build /Fo and /Fe with paths
    str fo = str_cat(self->arena, S("/Fo"), str_init_static(obj_file));
    str fe = str_cat(self->arena, S("/Fe"), str_init_static(self->out_path));

    // clang-format off
    { char const *_t = str_cstr(&fo); array_push(argv, _t); }
    { char const *_t = str_cstr(&fe); array_push(argv, _t); }

    { char const *_t = "/TC"; array_push(argv, _t); }
    array_push(argv, c_file);

    { char const *_t = null; array_push(argv, _t); }
    // clang-format on

    return argv;
}

#endif

int compile_c(state *self) {
    if (str_is_empty(self->program)) return 1;

    hires_timer cc_timer;
    hires_timer_init(&cc_timer);
    hires_timer_start(&cc_timer);

    size_t input_size = str_len(self->program);
    int    result     = 0;

#ifdef MOS_WINDOWS
    // Windows: use temp file (required for MSVC, simpler for all Windows compilers)
    platform_temp_file c_file, obj_file;
    if (platform_temp_file_create(&c_file, ".c")) return 1;
    if (platform_temp_file_create(&obj_file, ".obj")) return 1;

    FILE *f = fopen(c_file.path, "wb");
    if (!f) {
        fprintf(stderr, "failed to open temp file for writing\n");
        return 1;
    }
    fwrite(str_buf(&self->program), 1, str_len(self->program), f);
    fclose(f);
    str_deinit(self->arena, &self->program);

    c_string_array argv;
    if (is_msvc_compiler(self)) {
        argv = build_msvc_argv(self, null, 0, c_file.path, obj_file.path);
    } else {
        char const *extra[] = {"-Wno-unused-value", "-Wno-compare-distinct-pointer-types"};
        argv                = build_gcc_argv(self, extra, 2, c_file.path);
    }

    platform_exec_opts opts = {
      .argv       = (char const *const *)argv.v,
      .stdin_data = null,
      .stdin_len  = 0,
      .verbose    = self->verbose,
    };
    result = platform_exec(&opts);

    platform_temp_file_delete(&c_file);
    platform_temp_file_delete(&obj_file);
#else
    // Unix: pipe stdin to compiler
    char const        *extra[] = {"-Wno-unused-value", "-Wno-compare-distinct-pointer-types"};
    c_string_array     argv    = build_gcc_argv(self, extra, 2, null);

    platform_exec_opts opts    = {
         .argv       = (char const *const *)argv.v,
         .stdin_data = str_buf(&self->program),
         .stdin_len  = str_len(self->program),
         .verbose    = self->verbose,
    };
    result = platform_exec(&opts);
    str_deinit(self->arena, &self->program);
#endif

    hires_timer_stop(&cc_timer);
    if (self->report_stats) {
        self->stats.cc_time_ms    = hires_timer_elapsed_sec(&cc_timer) * 1000.0;
        self->stats.cc_input_size = input_size;
    }

    return result;
}

int compile_c_obj(state *self) {
    if (str_is_empty(self->program)) return 1;

    hires_timer cc_timer;
    hires_timer_init(&cc_timer);
    hires_timer_start(&cc_timer);

    size_t input_size = str_len(self->program);
    int    result     = 0;

#ifdef MOS_WINDOWS
    // Windows: use temp file (required for MSVC, simpler for all Windows compilers)
    platform_temp_file c_file, obj_file;
    if (platform_temp_file_create(&c_file, ".c")) return 1;
    if (platform_temp_file_create(&obj_file, ".obj")) return 1;

    FILE *f = fopen(c_file.path, "wb");
    if (!f) {
        fprintf(stderr, "failed to open temp file for writing\n");
        return 1;
    }
    fwrite(str_buf(&self->program), 1, str_len(self->program), f);
    fclose(f);
    str_deinit(self->arena, &self->program);

    c_string_array argv;
    if (is_msvc_compiler(self)) {
        char const *msvc_extra[] = {"/LD"};
        argv                     = build_msvc_argv(self, msvc_extra, 1, c_file.path, obj_file.path);
    } else {
        char const *extra[] = {"-fPIC", "-shared"};
        argv                = build_gcc_argv(self, extra, 2, c_file.path);
    }

    platform_exec_opts opts = {
      .argv       = (char const *const *)argv.v,
      .stdin_data = null,
      .stdin_len  = 0,
      .verbose    = self->verbose,
    };
    result = platform_exec(&opts);

    platform_temp_file_delete(&c_file);
    platform_temp_file_delete(&obj_file);
#else
    // Unix: pipe stdin to compiler
    char const        *extra[] = {"-fPIC", "-shared"};
    c_string_array     argv    = build_gcc_argv(self, extra, 2, null);

    platform_exec_opts opts    = {
         .argv       = (char const *const *)argv.v,
         .stdin_data = str_buf(&self->program),
         .stdin_len  = str_len(self->program),
         .verbose    = self->verbose,
    };
    result = platform_exec(&opts);
    str_deinit(self->arena, &self->program);
#endif

    hires_timer_stop(&cc_timer);
    if (self->report_stats) {
        self->stats.cc_time_ms    = hires_timer_elapsed_sec(&cc_timer) * 1000.0;
        self->stats.cc_input_size = input_size;
    }

    return result;
}

static int format_file(state *self) {
    char       *data;
    u32         size;
    char const *filename = "<stdin>";

    if (self->in_place && self->words.size <= 1) {
        fprintf(stderr, "error: cannot use --in-place with stdin\n");
        return 1;
    }

    if (self->words.size > 1) {
        filename = self->words.v[1];
        file_read(self->arena, filename, &data, &size);
        if (!data) return 1;
    } else {
        // Read all of stdin
        u32 capacity = 64 * 1024;
        data         = alloc_malloc(self->arena, capacity);
        size         = 0;
        for (;;) {
            size_t n = fread(data + size, 1, capacity - size, stdin);
            size += (u32)n;
            if (n == 0) {
                if (ferror(stdin)) {
                    perror("error reading stdin");
                    return 1;
                }
                break;
            }

            if (size == capacity) {
                if (capacity > UINT32_MAX / 2) {
                    fprintf(stderr, "error: input too large\n");
                    return 1;
                }
                u32 new_cap = capacity * 2;
                data        = alloc_realloc(self->arena, data, new_cap);
                capacity    = new_cap;
            }
        }
    }

    str    result = tl_format(self->arena, data, size, filename);
    size_t len    = str_len(result);

    if (self->in_place) {
        FILE *f = fopen(filename, "wb");
        if (!f) {
            fprintf(stderr, "error: could not open '%s' for writing\n", filename);
            return 1;
        }
        if (len != fwrite(str_buf(&result), 1, len, f)) {
            perror("error writing to file");
            fclose(f);
            return 1;
        }
        fclose(f);
    } else {
        if (len != fwrite(str_buf(&result), 1, len, stdout)) {
            perror("error writing to stdout");
            return 1;
        }
    }

    return 0;
}

static int pack_files(state *self) {
    // Validate arguments
    if (!self->out_path) {
        fprintf(stderr, "error: -o option is required for pack command\n");
        return 1;
    }

    if (self->words.size < 2) {
        fprintf(stderr, "error: pack command requires input file(s)\n");
        usage(1, self->argv0);
        return 1;
    }

    // Get input files (skip command name)
    c_string_csized input_files = {.v = self->words.v + 1, .size = self->words.size - 1};

    // Compute base directory from first user input file (before dependency resolution)
    str first_input = str_init(self->arena, input_files.v[0]);
    str first_norm  = file_path_normalize(self->arena, first_input);
    str base_dir    = file_dirname(self->arena, first_norm);

    // Get all files in dependency order using existing infrastructure
    str_sized all_files = files_in_order(self, input_files, (str_sized){0});

    if (self->verbose) {
        fprintf(stderr, "Discovered modules:\n");
        str_array keys = str_map_sorted_keys(self->arena, self->scanner.modules_seen);
        forall(i, keys) {
            fprintf(stderr, "    %s\n", str_cstr(&keys.v[i]));
        }

        fprintf(stderr, "\nPacking modules:\n");
        // FIXME: print sorted module list
    }

    // Parse package.tl from CWD
    tl_package pkg = {0};
    if (tl_package_parse_file(self->arena, "package.tl", &pkg)) {
        return 1;
    }

    if (pkg.info.export_count == 0) {
        fprintf(stderr, "error: package.tl must declare at least one export() module for pack\n");
        return 1;
    }

    // Validate exported modules against scanned source
    tl_source_scanner_validate_result vresult =
      tl_source_scanner_validate(&self->scanner, pkg.info.exports, pkg.info.export_count, self->verbose);
    if (vresult.error_count > 0) {
        fprintf(stderr, "pack aborted: %d validation error(s)\n", vresult.error_count);
        return 1;
    }

    // Validate declared dependencies exist and versions match
    for (u32 i = 0; i < pkg.dep_count; i++) {
        tl_package_dep *dep       = &pkg.deps[i];
        str             tlib_path = resolve_tlib_path(self, dep, &pkg.info);
        if (str_is_empty(tlib_path)) {
            fprintf(stderr, "error: declared dependency '%s=%s' not found", str_cstr(&dep->name),
                    str_cstr(&dep->version));
            if (pkg.info.depend_path_count > 0) {
                fprintf(stderr, "; searched:");
                for (u32 j = 0; j < pkg.info.depend_path_count; j++) {
                    fprintf(stderr, " %s", str_cstr(&pkg.info.depend_paths[j]));
                }
            }
            fprintf(stderr, "\n");
            return 1;
        }
        tl_tlib_archive dep_archive;
        if (tl_tlib_read(self->arena, str_cstr(&tlib_path), &dep_archive)) {
            fprintf(stderr, "error: failed to read dependency '%s' from '%s'\n", str_cstr(&dep->name),
                    str_cstr(&tlib_path));
            return 1;
        }
        if (!str_eq(dep_archive.metadata.version, dep->version)) {
            fprintf(stderr, "error: dependency '%s' version mismatch: expected '%s', found '%s' in '%s'\n",
                    str_cstr(&dep->name), str_cstr(&dep->version), str_cstr(&dep_archive.metadata.version),
                    str_cstr(&tlib_path));
            return 1;
        }
    }

    // Build pack opts from package
    tl_tlib_pack_opts opts = {.verbose = self->verbose};
    opts.name              = str_cstr(&pkg.info.name);
    opts.version           = str_cstr(&pkg.info.version);
    opts.author            = str_is_empty(pkg.info.author) ? null : str_cstr(&pkg.info.author);
    opts.package_tl_path   = "package.tl";

    if (pkg.info.export_count > 0) {
        if (pkg.info.export_count > UINT16_MAX) {
            fprintf(stderr, "error: too many modules (%u, max %u)\n", pkg.info.export_count,
                    (unsigned)UINT16_MAX);
            return 1;
        }
        opts.modules      = pkg.info.exports;
        opts.module_count = (u16)pkg.info.export_count;
    }

    // Build depends array: "Name=Version" strings
    if (pkg.dep_count > 0) {
        if (pkg.dep_count > UINT16_MAX) {
            fprintf(stderr, "error: too many dependencies (%u, max %u)\n", pkg.dep_count,
                    (unsigned)UINT16_MAX);
            return 1;
        }

        opts.depends       = alloc_malloc(self->arena, pkg.dep_count * sizeof(str));
        opts.depends_count = (u16)pkg.dep_count;

        for (u32 i = 0; i < pkg.dep_count; i++) {
            opts.depends[i] = str_cat_3(self->arena, pkg.deps[i].name, S("="), pkg.deps[i].version);
        }
    }

    // Build depends_optional array
    if (pkg.optional_dep_count > 0) {
        if (pkg.optional_dep_count > UINT16_MAX) {
            fprintf(stderr, "error: too many optional dependencies (%u, max %u)\n", pkg.optional_dep_count,
                    (unsigned)UINT16_MAX);
            return 1;
        }
        opts.depends_optional       = alloc_malloc(self->arena, pkg.optional_dep_count * sizeof(str));
        opts.depends_optional_count = (u16)pkg.optional_dep_count;
        for (u32 i = 0; i < pkg.optional_dep_count; i++) {
            opts.depends_optional[i] =
              str_cat_3(self->arena, pkg.optional_deps[i].name, S("="), pkg.optional_deps[i].version);
        }
    }

    return tl_tlib_pack(self->arena, self->out_path, all_files, base_dir, self->resolver, opts);
}

static int validate_files(state *self) {
    if (self->words.size < 2) {
        fprintf(stderr, "error: validate command requires input file(s)\n");
        usage(1, self->argv0);
        return 1;
    }

    // Get input files (skip command name)
    c_string_csized input_files = {.v = self->words.v + 1, .size = self->words.size - 1};

    // Scan all files in dependency order (populates scanner.modules_seen)
    files_in_order(self, input_files, (str_sized){0});

    // Parse package.tl
    tl_package pkg = {0};
    if (tl_package_parse_file(self->arena, "package.tl", &pkg)) {
        return 1;
    }

    // Cross-check scanner results against exported modules
    tl_source_scanner_validate_result result =
      tl_source_scanner_validate(&self->scanner, pkg.info.exports, pkg.info.export_count, self->verbose);

    if (result.error_count > 0) {
        fprintf(stderr, "error: validation failed: %d error(s)\n", result.error_count);
        return 1;
    }

    if (result.warning_count > 0) {
        fprintf(stderr, "ok: validation passed with %d warning(s)\n", result.warning_count);
    } else {
        fprintf(stderr, "ok: validation passed\n");
    }

    return 0;
}

static int init_package(state *self) {
    (void)self;
    // Check if package.tl already exists
    str pkg_path = str_init_static("package.tl");
    if (file_exists(pkg_path)) {
        fprintf(stderr, "error: package.tl already exists\n");
        return 1;
    }

    // Use current directory name as package name
    char cwd[256];
    span cwd_s = {.buf = cwd, .len = sizeof cwd};
    if (!file_current_working_directory(cwd_s)) {
        fprintf(stderr, "error: cannot determine current directory\n");
        return 1;
    }
    char const *name = file_basename(cwd);

    FILE       *f    = fopen("package.tl", "wb");
    if (!f) {
        fprintf(stderr, "error: cannot create package.tl\n");
        return 1;
    }
    fprintf(f, "format(1)\n");
    fprintf(f, "package(\"%s\")\n", name);
    fprintf(f, "version(\"0.0.1\")\n");
    fclose(f);

    fprintf(stderr, "Created package.tl for package \"%s\"\n", name);

    return 0;
}

static int unpack_files(state *self) {
    // Validate arguments
    if (self->words.size < 2) {
        fprintf(stderr, "error: unpack command requires input archive\n");
        usage(1, self->argv0);
        return 1;
    }

    if (!self->unpack_list && !self->out_path) {
        // Default current directory.
        self->out_path = ".";
    }

    char const         *archive_path = self->words.v[1];

    tl_tlib_unpack_opts opts         = {
              .list_only = self->unpack_list,
              .verbose   = self->verbose,
    };

    return tl_tlib_unpack(self->arena, archive_path, self->out_path, opts);
}

int main(int argc, char *argv[]) {

    int         result = 0;
    char        buf[256];
    span        buf_s = {.buf = buf, .len = sizeof buf};

    hires_timer timer;
    hires_timer_init(&timer);

    if (!file_current_working_directory(buf_s)) {
        fprintf(stderr, "failed to determine current working directory.\n");
        exit(1);
    }

    state self;
    state_init(&self);
    state_gather_options(&self, argc, argv);

    // Auto-define DEBUG or NDEBUG based on optimization mode
    str auto_def = str_init(self.arena, self.optimize ? "NDEBUG" : "DEBUG");
    array_push(self.defines, auto_def);

    // Populate scanner defines from -D flags
    forall(i, self.defines) {
        tl_source_scanner_define(&self.scanner, self.defines.v[i]);
    }

    if (!self.no_standard_includes) {
        add_standard_include_paths(&self, buf);
    }

    get_c_compiler(&self);
    if (str_is_empty(self.cc)) {
        fprintf(stderr, "Could not locate a working C compiler. Set CC environment "
                        "variable and try again.");
        exit(1);
    }

    if (self.verbose) {
        fprintf(stderr, "Current working directory: %s\n", buf_s.buf);
        fprintf(stderr, "C compiler: %s\n", str_cstr(&self.cc));
        if (self.no_standard_includes) fprintf(stderr, "Ignoring standard include paths\n");
        import_resolver_print_paths(self.resolver);
        forall(i, self.defines) {
            fprintf(stderr, "-D %s\n", str_cstr(&self.defines.v[i]));
        }
    }

    if (self.help) usage(0, argv[0]);
    if (self.words.size == 0) usage(0, argv[0]);

    if (0 == strcmp("c", self.words.v[0])) {
        hires_timer_start(&timer);
        result = compile(&self);
    }

    else if (0 == strcmp("exe", self.words.v[0])) {
        hires_timer_start(&timer);
        if (!self.out_path) {
            fprintf(stderr, "error: -o option is missing\n");
            exit(1);
        }
        self.is_executable = 1;
        result             = compile(&self);
        if (result) goto done;
        result = compile_c(&self);
    }

    else if (0 == strcmp("fmt", self.words.v[0])) {
        result = format_file(&self);
    }

    else if (0 == strcmp("lib-emit-c", self.words.v[0])) {
        hires_timer_start(&timer);

        self.is_library = 1;
        result          = compile(&self);
        output_program(&self);
    }

    else if (0 == strcmp("lib", self.words.v[0])) {
        hires_timer_start(&timer);
        if (!self.out_path) {
            fprintf(stderr, "error: -o option is missing\n");
            exit(1);
        }
        self.is_library = 1;
        result          = compile(&self);
        if (result) goto done;
        result = compile_c_obj(&self);

        // Write c_export header file if any exports were found
        if (!result && !str_is_empty(self.header)) {
            // Derive header path: strip extension, add .h
            size_t out_len = strlen(self.out_path);
            if (out_len + 3 > 4096) {
                fprintf(stderr, "error: output path too long for header generation\n");
                result = 1;
            } else {
                char  header_path[4096];
                snprintf(header_path, sizeof header_path, "%s", self.out_path);
                char *dot = strrchr(header_path, '.');
                if (dot) *dot = '\0';
                strncat(header_path, ".h", sizeof header_path - strlen(header_path) - 1);

                FILE *hf = fopen(header_path, "w");
                if (!hf) {
                    fprintf(stderr, "error: could not open header file for writing: %s\n", header_path);
                    result = 1;
                } else {
                    size_t len     = str_len(self.header);
                    size_t written = fwrite(str_buf(&self.header), 1, len, hf);
                    if (written != len || fclose(hf)) {
                        fprintf(stderr, "error: failed to write header file: %s\n", header_path);
                        result = 1;
                    }
                }
            }
        }
    }

    else if (0 == strcmp("pack", self.words.v[0])) {
        result = pack_files(&self);
    }

    else if (0 == strcmp("validate", self.words.v[0])) {
        result = validate_files(&self);
    }

    else if (0 == strcmp("unpack", self.words.v[0])) {
        result = unpack_files(&self);
    }

    else if (0 == strcmp("init", self.words.v[0])) {
        result = init_package(&self);
    }

done:
    hires_timer_stop(&timer);

    if (self.report_stats && !result) {
        print_stats_header();
        print_stats_row("Parsing", self.stats.parse_time_ms, self.stats.parse_peak_mem,
                        self.stats.parse_final_mem);
        print_stats_row("Type Inference", self.stats.infer_time_ms, self.stats.infer_peak_mem,
                        self.stats.infer_final_mem);
        print_stats_row("Transpilation", self.stats.transpile_time_ms, self.stats.transpile_peak_mem,
                        self.stats.transpile_final_mem);

        double total_ms =
          self.stats.parse_time_ms + self.stats.infer_time_ms + self.stats.transpile_time_ms;
        size_t total_peak =
          self.stats.parse_peak_mem + self.stats.infer_peak_mem + self.stats.transpile_peak_mem;

        // C compilation phase (only for exe/lib commands)
        if (self.is_executable || self.is_library) {
            print_stats_row_no_mem("C Compilation", self.stats.cc_time_ms, self.stats.cc_input_size);
            total_ms += self.stats.cc_time_ms;
        }

        print_stats_footer(total_ms, total_peak);

        // Inference sub-phase breakdown
        tl_infer_phase_stats const *ip = &self.stats.infer_phases;
        tl_infer_counters const    *ic = &self.stats.infer_counters;

        fprintf(stderr, "=== Type Inference Phases ===\n\n");
        fprintf(stderr, "%-24s %12s\n", "Sub-phase", "Time (ms)");
        fprintf(stderr, "%-24s %12s\n", "------------------------", "------------");
        fprintf(stderr, "%-24s %12.3f\n", "Alpha Conversion", ip->alpha_ms);
        fprintf(stderr, "%-24s %12.3f\n", "Load Toplevels", ip->load_toplevels_ms);
        fprintf(stderr, "%-24s %12.3f\n", "Generic Inference", ip->generic_inference_ms);
        fprintf(stderr, "%-24s %12.3f\n", "Free Variables", ip->free_vars_ms);
        fprintf(stderr, "%-24s %12.3f\n", "Specialization", ip->specialize_ms);
        fprintf(stderr, "%-24s %12.3f\n", "Tree Shaking", ip->tree_shake_ms);
        fprintf(stderr, "%-24s %12.3f\n", "Type Updates", ip->update_types_ms);
        fprintf(stderr, "\n");

        fprintf(stderr, "=== Inference Counters ===\n\n");
        fprintf(stderr, "Traversals (infer):        %u\n", ic->traverse_infer_calls);
        fprintf(stderr, "Traversals (specialize):   %u\n", ic->traverse_specialize_calls);
        fprintf(stderr, "Traversals (update types): %u\n", ic->traverse_update_types_calls);
        fprintf(stderr, "Nodes visited (total):     %llu\n",
                (unsigned long long)ic->traverse_nodes_visited);
        fprintf(stderr, "Specializations created:   %u\n", ic->specialize_created);
        fprintf(stderr, "Specialization cache hits: %u\n", ic->specialize_cache_hits);
        fprintf(stderr, "Already specialized:       %u\n", ic->specialize_already);
        fprintf(stderr, "Subs applications:         %u\n", ic->subs_apply_calls);
        fprintf(stderr, "Subs nodes visited:        %llu\n", (unsigned long long)ic->subs_nodes_visited);
        fprintf(stderr, "Unifications:              %u\n", ic->unify_calls);
        fprintf(stderr, "Unification time:          %.3f ms\n", ic->unify_ms);
        fprintf(stderr, "\n");

        fprintf(stderr, "=== Toplevel Survival ===\n\n");
        fprintf(stderr, "Inferred (Phase 3):        %u\n", ic->toplevels_inferred);
        fprintf(stderr, "After specialize (Phase 5): %u\n", ic->toplevels_after_specialize);
        fprintf(stderr, "After tree shake (Phase 6): %u\n", ic->toplevels_after_tree_shake);
        fprintf(stderr, "\n");

        fprintf(stderr, "=== Specialization Inner Loop ===\n\n");
        fprintf(stderr, "Clone + alpha-rename:      %.3f ms\n", ic->specialize_clone_ms);
        fprintf(stderr, "Re-inference:              %.3f ms\n", ic->specialize_infer_ms);
        fprintf(stderr, "Subs application:          %.3f ms\n", ic->specialize_subs_ms);
        fprintf(stderr, "Recursive specialize:      %.3f ms\n", ic->specialize_recurse_ms);
        fprintf(stderr, "\n");

        fprintf(stderr, "=== Type Updates Breakdown ===\n\n");
        fprintf(stderr, "Env pass:                  %.3f ms  (%u entries)\n", ic->update_types_env_ms,
                ic->update_types_env_count);
        fprintf(stderr, "AST traverse pass:         %.3f ms  (%u toplevels)\n", ic->update_types_ast_ms,
                ic->traverse_update_types_calls);
        fprintf(stderr, "Type constructor calls:     %u (skipped: %u)\n", ic->update_types_type_cons_calls,
                ic->update_types_type_cons_skipped);
        fprintf(stderr, "\n");
    }

    if (self.report_time) {
        double elapsed = hires_timer_elapsed_sec(&timer);
        double ms      = elapsed * 1000;
        fprintf(stderr, "Elapsed time: %0.6fms\n", ms);
    }

    state_deinit(&self);
    return result;
}
