#include "alloc.h"
#include "array.h"
#include "file.h"
#include "infer.h"
#include "parser.h"
#include "str.h"
#include "transpile.h"
#include "types.h"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdnoreturn.h>
#include <string.h>

#include <sys/wait.h>
#include <unistd.h>

// -- embed externs --
extern char const *embed_std_tl;

typedef struct {
    allocator      *arena;

    char const     *argv0;
    char const     *out_path;

    c_string_carray words;

    str             cc;
    str_sized       cflags;
    str_array       include_paths;

    str             program; // generated by compile()

    int             verbose;
    int             verbose_parse;
    int             help;
    int             optimize;

    int             is_library;
    int             is_executable;
} state;

noreturn void usage(int status, char const *argv0) {
    char const *progname = file_basename(argv0);

    printf("Usage: %s [-hv] [c | repl] [-o outpath] [path1 path2 ... pathn] \n", progname);
    puts("Commands:\n");
    printf("    c                      transpile input files to C\n");
    printf("    exe                    compile and create executable (-o required)\n");
    printf("\nOptions:\n");
    printf("    -h                     print usage\n");
    printf("    -I <path>              add <path> to import search path. Multiple ok.\n");
    printf("    -o <path>              write output to path instead of stdout\n");
    printf("    -O                     optimize C build (with -O2). Use CFLAGS for other flags.\n");
    printf("    -v                     verbose logging\n");
    printf("    --verbose-parse        produce large amount of parse progress output\n");
    exit(status);
}

void state_init(state *self) {
    alloc_zero(self);
    self->arena    = arena_create(default_allocator(), 4096);
    self->argv0    = null;
    self->out_path = null;
    self->words    = (c_string_carray){.alloc = self->arena};
    array_reserve(self->words, 32);
    self->cc            = str_empty();
    self->cflags        = (str_sized){0};
    self->include_paths = (str_array){.alloc = self->arena};
    self->program       = str_empty();
    self->verbose       = 0;
    self->verbose_parse = 0;
    self->help          = 0;
    self->optimize      = 0;
    self->is_library    = 0;
    self->is_executable = 0;
}

void state_deinit(state *self) {
    arena_destroy(default_allocator(), &self->arena);

    alloc_invalidate(self);
}

void state_gather_single_options(state *self, char *str) {
    u32 len = (u32)strlen(str);
    for (u32 i = 1; i < len; ++i) {
        switch (str[i]) {
        case 'h': self->help = 1; break;
        case 'v': self->verbose = 1; break;
        case 'O': self->optimize = 1; break;
        default:  break;
        }
    }
}

void state_gather_long_option(state *self, char *str) {
    if (0 == strcmp("--verbose-parse", str)) self->verbose_parse = 1;
}

void state_gather_options(state *self, int argc, char *argv[]) {

    self->argv0 = argv[0];

    for (int i = 1; i < argc; ++i) {
        if ('-' == argv[i][0]) {

            if (0 == strcmp("-o", argv[i])) {
                self->out_path = argv[++i];
                continue;
            } else if (0 == strcmp("-I", argv[i])) {
                str path = str_init(self->arena, argv[++i]);
                array_push(self->include_paths, path);
            } else if (0 == strncmp("--", argv[i], 2)) {
                state_gather_long_option(self, argv[i]);
            } else {
                state_gather_single_options(self, argv[i]);
            }

        } else {
            array_push(self->words, argv[i]);
        }
    }
}

void eval_print(char *in) {
    printf("you said: '%s'\n", in);
}

void read_import_lines(char_csized input, str_array *output) {
    // Note: output includes surrounding "..." marks for reasons
    u32         pos = 0, capture_start = 0;
    char const *data                                            = input.v;
    u32         size                                            = input.size;

    enum { start, noise, start_hash, in_hash, stop_hash } state = start;
    while (pos < size) {
        switch (state) {
        case start: {
            char c = data[pos++];
            if ('#' == c) state = start_hash;
            else if (isspace(c)) state = start;
            else state = noise;
        } break;
        case noise: {
            char c = data[pos++];
            if ('\n' == c) state = start;
        } break;
        case start_hash: {
            capture_start = pos;
            state         = in_hash;
        } break;
        case in_hash: {
            char c = data[pos++];
            if ('\n' == c) state = stop_hash;
        } break;
        case stop_hash: {
            str       command = str_init_n(output->alloc, &data[capture_start], pos - capture_start);
            str_array words   = {.alloc = output->alloc};
            str_parse_words(command, &words);
            if (words.size > 2 && str_eq(words.v[0], S("import"))) array_push(*output, words.v[1]);
            state = start;
        } break;
        }
    }

    if (stop_hash == state) {
        // catch command at end of file
        str       command = str_init_n(output->alloc, &data[capture_start], pos - capture_start);
        str_array words   = {.alloc = output->alloc};
        str_parse_words(command, &words);
        if (words.size > 2 && str_eq(words.v[0], S("import"))) array_push(*output, words.v[1]);
    }
}

static int is_quoted(str arg) {
    span s = str_span(&arg);
    if (s.buf[0] != '"' || s.buf[s.len - 1] != '"') return 0;
    return 1;
}

static int is_angle_quoted(str arg) {
    span s = str_span(&arg);
    if (s.buf[0] != '<' || s.buf[s.len - 1] != '>') return 0;
    return 1;
}

static str strip_quotes(allocator *alloc, str quoted) {
    // TODO: would be better to operate on spans so we don't needlessly copy strings
    if (!is_quoted(quoted) && !is_angle_quoted(quoted)) return str_empty();

    span s = str_span(&quoted);
    s.buf++;
    s.len -= 2;
    return str_copy_span(alloc, s);
}

static void print_import_paths(state *self) {
    fprintf(stderr, "info:  include paths:");
    forall(i, self->include_paths) {
        fprintf(stderr, " %s", str_cstr(&self->include_paths.v[i]));
    }
    fprintf(stderr, "\n");
}

static str find_import_file(state *self, str path) {
    // Note: path must be quoted, either with quotes or angle brackets
    if (!is_quoted(path) && !is_angle_quoted(path)) return str_empty();

    path = strip_quotes(self->arena, path);
    if (file_exists(str_cstr(&path))) return path;

    forall(i, self->include_paths) {
        str prefixed = str_cat_3(self->arena, self->include_paths.v[i], S("/"), path);
        if (file_exists(str_cstr(&prefixed))) {
            return prefixed;
        }
    }

    fprintf(stderr, "error: import not found: '%s'\n", str_cstr(&path));
    print_import_paths(self);
    exit(1);
}

static void collect_imports_from_import_file(state *self, str path, str_array *imports) {
    char *data;
    u32   size;

    if (str_is_empty(path)) return;

    path = find_import_file(self, path);
    file_read(imports->alloc, str_cstr(&path), &data, &size);

    str_array file_imports = {.alloc = imports->alloc};
    array_reserve(file_imports, 32);

    read_import_lines((char_csized){.size = size, .v = data}, &file_imports);
    forall(i, file_imports) {
        array_push(*imports, file_imports.v[i]);
        collect_imports_from_import_file(self, file_imports.v[i], imports);
    }
}

static void collect_imports_from_file(state *self, str path, str_array *imports) {
    char *data;
    u32   size;

    file_read(imports->alloc, str_cstr(&path), &data, &size);

    str_array file_imports = {.alloc = imports->alloc};
    array_reserve(file_imports, 32);

    read_import_lines((char_csized){.size = size, .v = data}, &file_imports);
    forall(i, file_imports) {
        array_push(*imports, file_imports.v[i]);
        collect_imports_from_import_file(self, file_imports.v[i], imports);
    }
}

static str_sized collect_imports(state *self, c_string_csized files) {
    allocator *alloc  = self->arena;

    char_array buffer = {.alloc = alloc};
    array_reserve(buffer, 64 * 1024);

    str_array imports = {.alloc = alloc};
    array_reserve(imports, 32);

    forall(i, files) {
        collect_imports_from_file(self, str_init_static(files.v[i]), &imports);
    }

    return (str_sized)array_sized(imports);
}

static str_sized files_in_order(state *self, c_string_csized files) {

    str_sized imports        = collect_imports(self, files);

    str_array files_in_order = {.alloc = self->arena};
    array_reserve(files_in_order, imports.size + files.size);

    str builtin = find_import_file(self, S("<builtin.tl>"));
    if (str_is_empty(builtin)) {
        fprintf(stderr, "error: failed to find 'builtin.tl'\n");
        print_import_paths(self);
        exit(1);
    }
    array_push(files_in_order, builtin);

    forall(i, imports) {
        // resolve file paths and strip quotes
        str file = imports.v[i];
        file     = find_import_file(self, file);
        array_push(files_in_order, file);
    }

    forall(i, files) {
        str file = str_init(self->arena, files.v[i]);
        array_push(files_in_order, file);
    }

    return (str_sized)array_sized(files_in_order);
}

//

static void get_c_compiler(state *self) {
    char const *CC = getenv("CC");
    if (CC) self->cc = str_init(self->arena, CC);
    else if (0 == system("command -v cc &> /dev/null")) self->cc = str_init(self->arena, "cc");
    else if (0 == system("command -v gcc &> /dev/null")) self->cc = str_init(self->arena, "gcc");
    else if (0 == system("command -v clang &> /dev/null")) self->cc = str_init(self->arena, "clang");
    else self->cc = str_empty();

    char const *CFLAGS = getenv("CFLAGS");

    if (CFLAGS) {
        str       cflags = str_init(self->arena, CFLAGS);
        str_array arr    = {.alloc = self->arena};
        str_parse_words(cflags, &arr);
        self->cflags = (str_sized)array_sized(arr);
    } else {
        self->cflags = (str_sized){0};
    }
}

int compile(state *self) {
    if (self->words.size < 2) usage(1, self->argv0);

    int             error       = 0;

    c_string_csized paths       = {.v = &self->words.v[1], .size = self->words.size - 1};

    tl_infer_opts   infer_opts  = {.is_library = self->is_library};
    tl_infer       *infer       = tl_infer_create(default_allocator(), &infer_opts);

    parser_opts     parser_opts = {
          .registry = tl_infer_get_registry(infer),
          .files    = files_in_order(self, paths),
    };
    parser *parser = parser_create(default_allocator(), &parser_opts);
    if (!parser) fatal("could not create parser");

    allocator     *nodes_alloc = arena_create(default_allocator(), 64 * 1024);
    ast_node_array nodes       = {.alloc = nodes_alloc};

    if (self->verbose_parse) {
        if (parser_parse_all_verbose(parser, &nodes)) {
            parser_report_errors(parser);
            ++error;
            goto cleanup_parser;
        }
    } else {
        if (parser_parse_all(parser, &nodes)) {
            parser_report_errors(parser);
            ++error;
            goto cleanup_parser;
        }
    }

    tl_infer_result infer_result = {0};
    tl_infer_set_verbose(infer, self->verbose);
    if (tl_infer_run(infer, (ast_node_sized)sized_all(nodes), &infer_result)) {
        tl_infer_report_errors(infer);
        error++;
        goto cleanup_ti;
    }

    transpile_opts transpile_opts = {.infer_result = infer_result, .is_library = self->is_library};
    transpile     *transpile      = transpile_create(default_allocator(), &transpile_opts);

    str_build      program_build;
    if (transpile_compile(transpile, &program_build)) goto cleanup_tp;

    str program = str_build_finish(&program_build);

    if (self->is_executable) {
        // Save program and return to caller
        self->program = program;
        goto done;
    } else {
        // output C source code
        if (self->out_path) {
            FILE *f = fopen(self->out_path, "wb");
            if (!f) fatal("could not open output file: '%s'", self->out_path);

            fprintf(f, "%.*s", str_ilen(program), str_buf(&program));

            fclose(f);
        } else {
            printf("%.*s", str_ilen(program), str_buf(&program));
        }
    }
    str_deinit(default_allocator(), &program);

done:
cleanup_tp:
    transpile_destroy(default_allocator(), &transpile);

cleanup_ti:
    tl_infer_destroy(default_allocator(), &infer);

cleanup_parser:
    parser_destroy(&parser);
    array_free(nodes);
    arena_destroy(default_allocator(), &nodes_alloc);
    return error;
}

int compile_c(state *self) {
    if (str_is_empty(self->program)) return 1;

    int stdin_pipe[2], stdout_pipe[2], stderr_pipe[2];
    if (pipe(stdin_pipe) == -1 || pipe(stdout_pipe) == -1 || pipe(stderr_pipe) == -1) {
        perror("pipe failed");
        return 1;
    }

    pid_t pid = fork();
    if (pid == -1) {
        perror("fork failed");
        return 1;
    }

    int child_res = 0;

    if (pid == 0) {
        // child process
        close(stdin_pipe[1]);
        close(stdout_pipe[0]);
        close(stderr_pipe[0]);
        dup2(stdin_pipe[0], STDIN_FILENO);
        dup2(stdout_pipe[1], STDOUT_FILENO);
        dup2(stderr_pipe[1], STDERR_FILENO);
        close(stdin_pipe[0]);
        close(stdout_pipe[1]);
        close(stderr_pipe[1]);

        char const *cc = str_cstr(&self->cc);

        // cflags
        c_string_array argv = {.alloc = self->arena};
        array_reserve(argv, self->cflags.size + 8);
        array_push(argv, cc);

        array_push_val(argv, "-o");
        array_push(argv, self->out_path);

        if (self->optimize) {
            array_push_val(argv, "-O2");
        }

        forall(i, self->cflags) {
            char const *cstr = str_cstr(&self->cflags.v[i]);
            array_push(argv, cstr);
        }

        array_push_val(argv, "-x");
        array_push_val(argv, "c");
        array_push_val(argv, "-");

        array_push_val(argv, null);

        // char *envp[] = {null};
        child_res = execvp(cc, argv.v);
        perror("exec failed");

    } else {
        // parent process
        close(stdin_pipe[0]);
        close(stdout_pipe[1]);
        close(stderr_pipe[1]);

        write(stdin_pipe[1], str_buf(&self->program), str_len(self->program));
        close(stdin_pipe[1]);

        // read stderr
        char  buf[1024];
        FILE *stderr_file = fdopen(stderr_pipe[0], "r");
        while (fgets(buf, sizeof(buf), stderr_file)) fprintf(stderr, "%s", buf);
        fclose(stderr_file);

        wait(null);
    }
    return child_res;
}

int main(int argc, char *argv[]) {

    int  result = 0;
    char buf[256];
    span buf_s = {.buf = buf, .len = sizeof buf};

    if (!file_current_working_directory(buf_s)) {
        fprintf(stderr, "failed to determine current working directory.\n");
        exit(1);
    }

    state self;
    state_init(&self);
    state_gather_options(&self, argc, argv);

    get_c_compiler(&self);
    if (str_is_empty(self.cc)) {
        fprintf(stderr,
                "Could not locate a working C compiler. Set CC environment variable and try again.");
        exit(1);
    }

    if (self.verbose) {
        fprintf(stderr, "Current working directory: %s\n", buf_s.buf);
        fprintf(stderr, "C compiler: %s\n", str_cstr(&self.cc));
        forall(i, self.include_paths) {
            fprintf(stderr, "-I %s\n", str_cstr(&self.include_paths.v[i]));
        }
    }

    if (self.help) usage(0, argv[0]);
    if (self.words.size == 0) usage(0, argv[0]);

    if (0 == strcmp("c", self.words.v[0])) {
        result = compile(&self);
    }

    else if (0 == strcmp("exe", self.words.v[0])) {
        if (!self.out_path) {
            fprintf(stderr, "error: -o option is missing\n");
            exit(1);
        }
        self.is_executable = 1;
        result             = compile(&self);
        if (result) goto done;
        result = compile_c(&self);

    }

    else if (0 == strcmp("lib", self.words.v[0])) {
        self.is_library = 1;
        result          = compile(&self);
    }

done:
    state_deinit(&self);
    return result;
}
