#include "alloc.h"
#include "array.h"
#include "file.h"
#include "format.h"
#include "hashmap.h"
#include "import_resolver.h"
#include "infer.h"
#include "parser.h"
#include "str.h"
#include "tlib.h"
#include "transpile.h"
#include "types.h"

#include "platform.h"

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdnoreturn.h>
#include <string.h>

// -- embed externs --
extern char const *embed_prelude_tl;

#include "version.h"

typedef struct {
    allocator       *arena;

    char const      *argv0;
    char const      *out_path;

    c_string_carray  words;

    str              cc;
    str_sized        cflags;
    import_resolver *resolver;
    str_array        defines;
    hashmap         *import_defines; // hset for conditional compilation during import resolution
    int              import_skip_depth;

    str              program; // generated by compile()

    int              no_line_directive;
    int              no_standard_includes;
    int              verbose;
    int              verbose_ast;
    int              verbose_parse;
    int              report_time;  // --time option
    int              report_stats; // --stats option
    int              help;
    int              optimize;

    int              in_place;

    int              is_library;
    int              is_executable;

    // Compilation statistics (populated when report_stats is set)
    struct {
        double parse_time_ms;
        size_t parse_peak_mem;
        size_t parse_final_mem;
        double infer_time_ms;
        size_t infer_peak_mem;
        size_t infer_final_mem;
        double transpile_time_ms;
        size_t transpile_peak_mem;
        size_t transpile_final_mem;
        double cc_time_ms;
        size_t cc_input_size; // Size of C source passed to compiler
    } stats;
} state;

noreturn void usage(int status, char const *argv0) {
    char const *progname = file_basename(argv0);

    printf("Usage: %s [-hv] <command> [-o outpath] [path1 path2 ... pathn] \n", progname);
    puts("Commands:\n");
    printf("    c                      transpile input files to C\n");
    printf("    exe                    compile and create executable (-o required)\n");
    printf("    fmt                    format source file (reads stdin if no file given)\n");
    printf("    lib                    compile and create shared library (-o required)\n");
    printf("    lib-emit-c             transpile input files to C as library source code\n");
    printf("    pack                   create .tlib archive from source files (-o required)\n");
    printf("\nOptions:\n");
    printf("    -h                     print usage and exit\n");
    printf("    -V, --version          print version and exit\n");
    printf("    -D <symbol>            define <symbol> for conditional compilation\n");
    printf("    -I <path>              add user include path for \"...\" imports. Multiple ok.\n");
    printf("    -S <path>              add standard library path for <...> imports. Multiple ok.\n");
    printf("    -o <path>              write output to path instead of stdout\n");
    printf("    -i, --in-place         overwrite file in place (fmt command only)\n");
    printf("    -O                     optimize C build (with -O2). Use CFLAGS for other flags.\n");
    printf("    -v                     verbose logging\n");
    printf("    --no-line-directive    suppress output of #line directives in C file\n");
    printf("    --no-standard-includes do not add default standard library paths\n");
    printf("    --stats                report memory and time statistics per phase\n");
    printf("    --time                 report elapsed time of compilation process\n");
    printf("    --verbose-ast          produce full recursive ast output when -v is set\n");
    printf("    --verbose-parse        produce large amount of parse progress output\n");
    exit(status);
}

noreturn void version() {
    printf("%s\n", TESS_VERSION);
    exit(0);
}

void state_init(state *self) {
    alloc_zero(self);
    self->arena    = arena_create(default_allocator(), 4096);
    self->argv0    = null;
    self->out_path = null;
    self->words    = (c_string_carray){.alloc = self->arena};
    array_reserve(self->words, 32);
    self->cc                   = str_empty();
    self->cflags               = (str_sized){0};
    self->resolver             = import_resolver_create(self->arena);
    self->defines              = (str_array){.alloc = self->arena};
    self->import_defines       = hset_create(self->arena, 8);
    self->program              = str_empty();
    self->verbose              = 0;
    self->verbose_ast          = 0;
    self->verbose_parse        = 0;
    self->report_time          = 0;
    self->report_stats         = 0;
    self->no_line_directive    = 0;
    self->no_standard_includes = 0;
    self->help                 = 0;
    self->optimize             = 0;
    self->in_place             = 0;
    self->is_library           = 0;
    self->is_executable        = 0;
}

void state_deinit(state *self) {
    arena_destroy(&self->arena);

    alloc_invalidate(self);
}

void state_gather_single_options(state *self, char *str) {
    u32 len = (u32)strlen(str);
    for (u32 i = 1; i < len; ++i) {
        switch (str[i]) {
        case 'h': self->help = 1; break;
        case 'v': self->verbose = 1; break;
        case 'V': version(); break;
        case 'i': self->in_place = 1; break;
        case 'O': self->optimize = 1; break;
        default:  usage(1, self->argv0); break;
        }
    }
}

void state_gather_long_option(state *self, char *str) {
    if (0 == strcmp("--version", str)) version();
    else if (0 == strcmp("--verbose-ast", str)) self->verbose_ast = 1;
    else if (0 == strcmp("--verbose-parse", str)) self->verbose_parse = 1;
    else if (0 == strcmp("--no-line-directive", str)) self->no_line_directive = 1;
    else if (0 == strcmp("--no-standard-includes", str)) self->no_standard_includes = 1;
    else if (0 == strcmp("--in-place", str)) self->in_place = 1;
    else if (0 == strcmp("--time", str)) self->report_time = 1;
    else if (0 == strcmp("--stats", str)) self->report_stats = 1;
    else if (0 == strcmp("--", str)) /* ignore */
        ;
    else usage(1, self->argv0);
}

void state_gather_options(state *self, int argc, char *argv[]) {

    self->argv0 = argv[0];

    // Flags -o, -I, -D accept values with or without a space (e.g. -ofoo or -o foo).
    for (int i = 1; i < argc; ++i) {
        if ('-' == argv[i][0]) {

            if (0 == strncmp("-o", argv[i], 2)) {
                self->out_path = argv[i][2] ? argv[i] + 2 : argv[++i];
                continue;
            } else if (0 == strncmp("-I", argv[i], 2)) {
                char const *val  = argv[i][2] ? argv[i] + 2 : argv[++i];
                str         path = str_init(self->arena, val);
                import_resolver_add_user_path(self->resolver, path);
            } else if (0 == strncmp("-S", argv[i], 2)) {
                char const *val  = argv[i][2] ? argv[i] + 2 : argv[++i];
                str         path = str_init(self->arena, val);
                import_resolver_add_standard_path(self->resolver, path);
            } else if (0 == strncmp("-D", argv[i], 2)) {
                char const *sym    = argv[i][2] ? argv[i] + 2 : argv[++i];
                str         define = str_init(self->arena, sym);
                array_push(self->defines, define);
            } else if (0 == strncmp("--", argv[i], 2)) {
                state_gather_long_option(self, argv[i]);
            } else {
                state_gather_single_options(self, argv[i]);
            }

        } else {
            array_push(self->words, argv[i]);
        }
    }
}

void eval_print(char *in) {
    printf("you said: '%s'\n", in);
}

static void process_import_hash(state *self, str_array *output, char const *data, u32 capture_start,
                                u32 pos) {
    // Strip trailing newline so str_parse_words produces exact word counts.
    u32 len = pos - capture_start;
    if (len > 0 && data[pos - 1] == '\n') len -= 1;
    if (len > 0 && data[pos - 2] == '\r') len -= 1;

    str       command = str_init_n(output->alloc, &data[capture_start], len);
    str_array words   = {.alloc = output->alloc};
    str_parse_words(command, &words);

    // Conditional compilation: same logic as tokenizer.c stop_hash_command.
    // When skip_depth > 0, tokens are skipped. #ifdef/#ifndef always increment
    // skip_depth when already skipping (to match #endif pairs), but #define/#undef
    // and #import are only processed at depth 0.
    if (words.size == 1 && str_eq(words.v[0], S("endif"))) {
        if (self->import_skip_depth) self->import_skip_depth -= 1;
    } else if (words.size == 2) {
        if (0 == self->import_skip_depth && str_eq(words.v[0], S("define"))) {
            str_hset_insert(&self->import_defines, words.v[1]);
        } else if (0 == self->import_skip_depth && str_eq(words.v[0], S("undef"))) {
            str_hset_remove(self->import_defines, words.v[1]);
        } else if (str_eq(words.v[0], S("ifdef"))) {
            if (self->import_skip_depth || !str_hset_contains(self->import_defines, words.v[1]))
                self->import_skip_depth += 1;
        } else if (str_eq(words.v[0], S("ifndef"))) {
            if (self->import_skip_depth || str_hset_contains(self->import_defines, words.v[1]))
                self->import_skip_depth += 1;
        }
    }

    if (0 == self->import_skip_depth && words.size >= 2 && str_eq(words.v[0], S("import"))) {
        array_push(*output, words.v[1]);
    }
}

void read_import_lines(state *self, char_csized input, str_array *output) {
    // Note: output includes surrounding "..." marks for reasons
    u32         pos = 0, capture_start = 0;
    char const *data                                            = input.v;
    u32         size                                            = input.size;
    enum { start, noise, start_hash, in_hash, stop_hash } state = start;
    while (pos < size) {
        switch (state) {
        case start: {
            char c = data[pos++];
            if ('#' == c) state = start_hash;
            else if (isspace(c)) state = start;
            else state = noise;
        } break;
        case noise: {
            char c = data[pos++];
            if ('\n' == c) state = start;
        } break;
        case start_hash: {
            capture_start = pos;
            state         = in_hash;
        } break;
        case in_hash: {
            char c = data[pos++];
            if ('\n' == c) state = stop_hash;
        } break;
        case stop_hash: {
            process_import_hash(self, output, data, capture_start, pos);
            state = start;
        } break;
        }
    }

    if (stop_hash == state) {
        // catch command at end of file
        process_import_hash(self, output, data, capture_start, pos);
    }
}

static void print_import_paths(state *self) {
    import_resolver_print_paths(self->resolver);
}

static void add_standard_include_paths(state *self, char const *cwd) {
    char exe_buf[4096];
    span exe_span = {.buf = exe_buf, .len = sizeof(exe_buf)};

    // 1. Add <exe_dir>/../lib/tess/std (for installed tess)
    if (file_exe_directory(exe_span)) {
        str exe_dir       = str_init(self->arena, exe_buf);
        str installed_std = str_cat(self->arena, exe_dir, S("/../lib/tess/std"));
        import_resolver_add_standard_path(self->resolver, installed_std);
    }

    // 2. Add <cwd>/src/tl/std (for development builds)
    str cwd_std = str_cat(self->arena, str_init_static(cwd), S("/src/tl/std"));
    import_resolver_add_standard_path(self->resolver, cwd_std);
}

// Resolve an import path using the import resolver
// Returns empty string on error (error already printed)
static str resolve_import(state *self, str import_path, str importing_file) {
    import_result result = import_resolver_resolve(self->resolver, import_path, importing_file);

    if (str_is_empty(result.canonical_path)) {
        exit(1); // Error already printed by resolver
    }

    return result.canonical_path;
}

static void collect_imports_from_import_file(state *self, str import_path, str importing_file,
                                             str_array *imports, str_array *resolved_paths) {
    if (str_is_empty(import_path)) return;

    // Resolve the import path
    import_result result = import_resolver_resolve(self->resolver, import_path, importing_file);

    if (str_is_empty(result.canonical_path)) {
        exit(1); // Error already printed by resolver
    }

    // Skip if already imported (duplicate detection)
    if (result.is_duplicate) {
        return;
    }

    // Check for circular imports
    if (import_resolver_begin_import(self->resolver, result.canonical_path)) {
        fprintf(stderr, "error: circular import detected: %s\n", str_cstr(&result.canonical_path));
        exit(1);
    }

    // Mark as imported
    import_resolver_mark_imported(self->resolver, result.canonical_path);

    // Read file and collect its imports
    char *data;
    u32   size;
    file_read(imports->alloc, str_cstr(&result.canonical_path), &data, &size);

    str_array file_imports = {.alloc = imports->alloc};
    array_reserve(file_imports, 32);

    read_import_lines(self, (char_csized){.size = size, .v = data}, &file_imports);

    // Recursively collect imports from this file
    forall(i, file_imports) {
        collect_imports_from_import_file(self, file_imports.v[i], result.canonical_path, imports,
                                         resolved_paths);
    }

    // Add to output after processing dependencies (topological order)
    array_push(*imports, import_path);
    array_push(*resolved_paths, result.canonical_path);

    // Mark import as complete
    import_resolver_end_import(self->resolver, result.canonical_path);
}

static void collect_imports_from_file(state *self, str path, str_array *imports,
                                      str_array *resolved_paths) {
    char *data;
    u32   size;

    file_read(imports->alloc, str_cstr(&path), &data, &size);

    str_array file_imports = {.alloc = imports->alloc};
    array_reserve(file_imports, 32);

    read_import_lines(self, (char_csized){.size = size, .v = data}, &file_imports);
    forall(i, file_imports) {
        collect_imports_from_import_file(self, file_imports.v[i], path, imports, resolved_paths);
    }
}

// Collect all imports from the given files
// Returns the resolved paths in dependency order
static str_sized collect_imports(state *self, c_string_csized files) {
    allocator *alloc          = self->arena;

    str_array  imports        = {.alloc = alloc};
    str_array  resolved_paths = {.alloc = alloc};
    array_reserve(imports, 32);
    array_reserve(resolved_paths, 32);

    forall(i, files) {
        collect_imports_from_file(self, str_init_static(files.v[i]), &imports, &resolved_paths);
    }

    return (str_sized)array_sized(resolved_paths);
}

static str_sized files_in_order(state *self, c_string_csized files) {
    // Collect all imports (resolved paths in dependency order)
    str_sized resolved_imports = collect_imports(self, files);

    str_array files_in_order   = {.alloc = self->arena};
    array_reserve(files_in_order, resolved_imports.size + files.size + 1);

    // Resolve builtin.tl (always first)
    str builtin = resolve_import(self, S("<builtin.tl>"), str_empty());
    if (str_is_empty(builtin)) {
        fprintf(stderr, "error: failed to find 'builtin.tl'\n");
        print_import_paths(self);
        exit(1);
    }
    array_push(files_in_order, builtin);

    // Add resolved imports (already in correct order)
    forall(i, resolved_imports) {
        array_push(files_in_order, resolved_imports.v[i]);
    }

    forall(i, files) {
        str file = str_init(self->arena, files.v[i]);
        array_push(files_in_order, file);
    }

    return (str_sized)array_sized(files_in_order);
}

//

static void output_program(state *self) {
    if (self->out_path) {
        FILE *f = fopen(self->out_path, "wb");
        if (!f) fatal("could not open output file: '%s'", self->out_path);

        fprintf(f, "%.*s", str_ilen(self->program), str_buf(&self->program));

        fclose(f);
    } else {
        printf("%.*s", str_ilen(self->program), str_buf(&self->program));
    }
}

static void get_c_compiler(state *self) {
    char const *CC = getenv("CC");
    if (CC) {
        self->cc = str_init(self->arena, CC);
    }
#ifdef MOS_WINDOWS
    else if (platform_command_exists("cl"))
        self->cc = str_init(self->arena, "cl");
    else if (platform_command_exists("clang")) self->cc = str_init(self->arena, "clang");
    else if (platform_command_exists("gcc")) self->cc = str_init(self->arena, "gcc");
#else
    else if (platform_command_exists("cc"))
        self->cc = str_init(self->arena, "cc");
    else if (platform_command_exists("gcc")) self->cc = str_init(self->arena, "gcc");
    else if (platform_command_exists("clang")) self->cc = str_init(self->arena, "clang");
#endif
    else self->cc = str_empty();

    char const *CFLAGS = getenv("CFLAGS");

    if (CFLAGS) {
        str       cflags = str_init(self->arena, CFLAGS);
        str_array arr    = {.alloc = self->arena};
        str_parse_words(cflags, &arr);
        self->cflags = (str_sized)array_sized(arr);
    } else {
        self->cflags = (str_sized){0};
    }
}

// -- stats formatting helpers --

static void format_memory(char *buf, size_t sz, size_t bytes) {
    if (bytes < 1024) snprintf(buf, sz, "%zu B", bytes);
    else if (bytes < 1024 * 1024) snprintf(buf, sz, "%.1f KB", bytes / 1024.0);
    else snprintf(buf, sz, "%.2f MB", bytes / (1024.0 * 1024.0));
}

static void print_stats_header(void) {
    fprintf(stderr, "\n=== Compilation Statistics ===\n\n");
    fprintf(stderr, "%-20s %12s %12s %12s\n", "Phase", "Time (ms)", "Peak Mem", "Final Mem");
    fprintf(stderr, "%-20s %12s %12s %12s\n", "--------------------", "------------", "------------",
            "------------");
}

static void print_stats_row(char const *phase, double time_ms, size_t peak_mem, size_t final_mem) {
    char peak_buf[32], final_buf[32];
    format_memory(peak_buf, sizeof peak_buf, peak_mem);
    format_memory(final_buf, sizeof final_buf, final_mem);
    fprintf(stderr, "%-20s %12.3f %12s %12s\n", phase, time_ms, peak_buf, final_buf);
}

static void print_stats_row_no_mem(char const *phase, double time_ms, size_t input_size) {
    char size_buf[32];
    format_memory(size_buf, sizeof size_buf, input_size);
    fprintf(stderr, "%-20s %12.3f %12s %12s\n", phase, time_ms, "-", size_buf);
}

static void print_stats_footer(double total_ms, size_t total_peak) {
    char peak_buf[32];
    format_memory(peak_buf, sizeof peak_buf, total_peak);
    fprintf(stderr, "%-20s %12s %12s %12s\n", "--------------------", "------------", "------------",
            "------------");
    fprintf(stderr, "%-20s %12.3f %12s\n", "TOTAL", total_ms, peak_buf);
    fprintf(stderr, "\n");
}

int compile(state *self) {
    if (self->words.size < 2) usage(1, self->argv0);

    int error = 0;

    // Stats collection
    hires_timer phase_timer;
    hires_timer_init(&phase_timer);

    c_string_csized paths       = {.v = &self->words.v[1], .size = self->words.size - 1};

    tl_infer_opts   infer_opts  = {.is_library = self->is_library};
    tl_infer       *infer       = tl_infer_create(default_allocator(), &infer_opts);

    parser_opts     parser_opts = {
          .registry = tl_infer_get_registry(infer),
          .files    = files_in_order(self, paths),
          .prelude  = embed_prelude_tl,
          .defines  = self->defines,
    };

    // === PARSING PHASE ===
    hires_timer_start(&phase_timer);

    parser *parser = parser_create(default_allocator(), &parser_opts);
    if (!parser) fatal("could not create parser");
    parser_set_verbose(parser, self->verbose_parse);

    allocator     *nodes_alloc = arena_create(default_allocator(), 64 * 1024);
    ast_node_array nodes       = {.alloc = nodes_alloc};

    // parser first pass
    if (parser_parse_all_symbols(parser)) {
        parser_report_errors(parser);
        ++error;
        goto cleanup_parser;
    }

    hashmap *syms = parser_take_module_symbols(parser);
    parser_destroy(&parser);

    // parser second pass
    parser = parser_create(default_allocator(), &parser_opts);

    parser_set_module_symbols(parser, syms);

    if (self->verbose_parse) {
        if (parser_parse_all_verbose(parser, &nodes)) {
            parser_report_errors(parser);
            ++error;
            goto cleanup_parser;
        }
    } else {
        if (parser_parse_all(parser, &nodes)) {
            parser_report_errors(parser);
            ++error;
            goto cleanup_parser;
        }
    }

    hires_timer_stop(&phase_timer);
    if (self->report_stats) {
        self->stats.parse_time_ms = hires_timer_elapsed_sec(&phase_timer) * 1000.0;
        arena_stats ast_stats, token_stats;
        parser_get_arena_stats(parser, &ast_stats, &token_stats);
        self->stats.parse_peak_mem  = ast_stats.peak_allocated + token_stats.peak_allocated;
        self->stats.parse_final_mem = ast_stats.allocated + token_stats.allocated;
    }

    // === TYPE INFERENCE PHASE ===
    hires_timer_start(&phase_timer);

    tl_infer_result infer_result = {0};
    tl_infer_set_verbose(infer, self->verbose);
    tl_infer_set_verbose_ast(infer, self->verbose_ast);
    if (tl_infer_run(infer, (ast_node_sized)sized_all(nodes), &infer_result)) {
        tl_infer_report_errors(infer);
        error++;
        goto cleanup_ti;
    }

    hires_timer_stop(&phase_timer);
    if (self->report_stats) {
        self->stats.infer_time_ms = hires_timer_elapsed_sec(&phase_timer) * 1000.0;
        arena_stats infer_arena_stats;
        tl_infer_get_arena_stats(infer, &infer_arena_stats);
        self->stats.infer_peak_mem  = infer_arena_stats.peak_allocated;
        self->stats.infer_final_mem = infer_arena_stats.allocated;
    }

    // === TRANSPILATION PHASE ===
    hires_timer_start(&phase_timer);

    transpile_opts transpile_opts = {
      .infer_result      = infer_result,
      .is_library        = self->is_library,
      .no_line_directive = self->no_line_directive,
      .verbose           = self->verbose,
    };
    transpile *transpile = transpile_create(default_allocator(), &transpile_opts);

    str_build  program_build;
    if (transpile_compile(transpile, &program_build)) goto cleanup_tp;

    hires_timer_stop(&phase_timer);
    if (self->report_stats) {
        self->stats.transpile_time_ms = hires_timer_elapsed_sec(&phase_timer) * 1000.0;
        arena_stats tp_arena_stats;
        transpile_get_arena_stats(transpile, &tp_arena_stats);
        self->stats.transpile_peak_mem  = tp_arena_stats.peak_allocated;
        self->stats.transpile_final_mem = tp_arena_stats.allocated;
    }

    str program = str_build_finish(&program_build);

    if (self->is_executable || self->is_library) {
        // Save program and return to caller
        self->program = program;
        goto done;
    } else {
        // output C source code
        self->program = program;
        output_program(self);
    }

    str_deinit(default_allocator(), &program);

done:
    // is_executable || is_library: Caller will take over program
cleanup_tp:
    transpile_destroy(default_allocator(), &transpile);

cleanup_ti:
    tl_infer_destroy(default_allocator(), &infer);

cleanup_parser:
    parser_destroy(&parser);
    array_free(nodes);
    arena_destroy(&nodes_alloc);
    return error;
}

#ifdef MOS_WINDOWS
static int is_msvc_compiler(state *self) {
    char const *cc = str_cstr(&self->cc);
    return (0 == strcmp(cc, "cl") || 0 == strcmp(cc, "cl.exe"));
}
#endif

// Build argv array for gcc/clang compiler invocation
// extra_flags: array of additional flags (e.g., "-shared", "-fPIC")
// extra_flags_count: number of additional flags
// use_temp_file: if non-null, use this temp file path; otherwise read from stdin
static c_string_array build_gcc_argv(state *self, char const **extra_flags, int extra_flags_count,
                                     char const *temp_file) {
    char const    *cc   = str_cstr(&self->cc);

    c_string_array argv = {.alloc = self->arena};
    array_reserve(argv, self->cflags.size + extra_flags_count + 16);
    array_push(argv, cc);

    // clang-format off
    { char const *_t = "-o"; array_push(argv, _t); }
    array_push(argv, self->out_path);
    // clang-format on

    if (self->optimize) {
        char const *_t = "-O2";
        array_push(argv, _t);
    }

    forall(i, self->cflags) {
        char const *cstr = str_cstr(&self->cflags.v[i]);
        array_push(argv, cstr);
    }

    // clang-format off
    { char const *_t = "-std=c11"; array_push(argv, _t); }
    { char const *_t = "-Wno-format-security"; array_push(argv, _t); }
    // clang-format on

    for (int i = 0; i < extra_flags_count; i++) {
        array_push(argv, extra_flags[i]);
    }

    if (temp_file) {
        array_push(argv, temp_file);
    } else {
        // clang-format off
        { char const *_t = "-x"; array_push(argv, _t); }
        { char const *_t = "c"; array_push(argv, _t); }
        { char const *_t = "-"; array_push(argv, _t); }
        // clang-format on
    }

    {
        char const *_t = null;
        array_push(argv, _t);
    }

    return argv;
}

#ifdef MOS_WINDOWS

// Build argv array for MSVC compiler invocation
// msvc_extra_flags: array of additional flags (e.g., "/LD")
// msvc_extra_flags_count: number of additional flags
// c_file: path to C source file
// obj_file: path for object file output
static c_string_array build_msvc_argv(state *self, char const **msvc_extra_flags,
                                      int msvc_extra_flags_count, char const *c_file,
                                      char const *obj_file) {
    c_string_array argv = {.alloc = self->arena};
    array_reserve(argv, self->cflags.size + msvc_extra_flags_count + 16);

    char const *cc = str_cstr(&self->cc);
    array_push(argv, cc);

    {
        char const *_t = "/nologo";
        array_push(argv, _t);
    }

    for (int i = 0; i < msvc_extra_flags_count; i++) {
        array_push(argv, msvc_extra_flags[i]);
    }

    if (self->optimize) {
        char const *_t = "/O2";
        array_push(argv, _t);
    }

    forall(i, self->cflags) {
        char const *cstr = str_cstr(&self->cflags.v[i]);
        array_push(argv, cstr);
    }

    // Build /Fo and /Fe with paths
    str fo = str_cat(self->arena, S("/Fo"), str_init_static(obj_file));
    str fe = str_cat(self->arena, S("/Fe"), str_init_static(self->out_path));

    // clang-format off
    { char const *_t = str_cstr(&fo); array_push(argv, _t); }
    { char const *_t = str_cstr(&fe); array_push(argv, _t); }

    { char const *_t = "/TC"; array_push(argv, _t); }
    array_push(argv, c_file);

    { char const *_t = null; array_push(argv, _t); }
    // clang-format on

    return argv;
}

#endif

int compile_c(state *self) {
    if (str_is_empty(self->program)) return 1;

    hires_timer cc_timer;
    hires_timer_init(&cc_timer);
    hires_timer_start(&cc_timer);

    size_t input_size = str_len(self->program);
    int    result     = 0;

#ifdef MOS_WINDOWS
    // Windows: use temp file (required for MSVC, simpler for all Windows compilers)
    platform_temp_file c_file, obj_file;
    if (platform_temp_file_create(&c_file, ".c")) return 1;
    if (platform_temp_file_create(&obj_file, ".obj")) return 1;

    FILE *f = fopen(c_file.path, "wb");
    if (!f) {
        fprintf(stderr, "failed to open temp file for writing\n");
        return 1;
    }
    fwrite(str_buf(&self->program), 1, str_len(self->program), f);
    fclose(f);
    str_deinit(default_allocator(), &self->program);

    c_string_array argv;
    if (is_msvc_compiler(self)) {
        argv = build_msvc_argv(self, null, 0, c_file.path, obj_file.path);
    } else {
        char const *extra[] = {"-Wno-unused-value", "-Wno-compare-distinct-pointer-types"};
        argv                = build_gcc_argv(self, extra, 2, c_file.path);
    }

    platform_exec_opts opts = {
      .argv       = (char const *const *)argv.v,
      .stdin_data = null,
      .stdin_len  = 0,
      .verbose    = self->verbose,
    };
    result = platform_exec(&opts);

    platform_temp_file_delete(&c_file);
    platform_temp_file_delete(&obj_file);
#else
    // Unix: pipe stdin to compiler
    char const        *extra[] = {"-Wno-unused-value", "-Wno-compare-distinct-pointer-types"};
    c_string_array     argv    = build_gcc_argv(self, extra, 2, null);

    platform_exec_opts opts    = {
         .argv       = (char const *const *)argv.v,
         .stdin_data = str_buf(&self->program),
         .stdin_len  = str_len(self->program),
         .verbose    = self->verbose,
    };
    result = platform_exec(&opts);
    str_deinit(default_allocator(), &self->program);
#endif

    hires_timer_stop(&cc_timer);
    if (self->report_stats) {
        self->stats.cc_time_ms    = hires_timer_elapsed_sec(&cc_timer) * 1000.0;
        self->stats.cc_input_size = input_size;
    }

    return result;
}

int compile_c_obj(state *self) {
    if (str_is_empty(self->program)) return 1;

    hires_timer cc_timer;
    hires_timer_init(&cc_timer);
    hires_timer_start(&cc_timer);

    size_t input_size = str_len(self->program);
    int    result     = 0;

#ifdef MOS_WINDOWS
    // Windows: use temp file (required for MSVC, simpler for all Windows compilers)
    platform_temp_file c_file, obj_file;
    if (platform_temp_file_create(&c_file, ".c")) return 1;
    if (platform_temp_file_create(&obj_file, ".obj")) return 1;

    FILE *f = fopen(c_file.path, "wb");
    if (!f) {
        fprintf(stderr, "failed to open temp file for writing\n");
        return 1;
    }
    fwrite(str_buf(&self->program), 1, str_len(self->program), f);
    fclose(f);
    str_deinit(default_allocator(), &self->program);

    c_string_array argv;
    if (is_msvc_compiler(self)) {
        char const *msvc_extra[] = {"/LD"};
        argv                     = build_msvc_argv(self, msvc_extra, 1, c_file.path, obj_file.path);
    } else {
        char const *extra[] = {"-fPIC", "-shared"};
        argv                = build_gcc_argv(self, extra, 2, c_file.path);
    }

    platform_exec_opts opts = {
      .argv       = (char const *const *)argv.v,
      .stdin_data = null,
      .stdin_len  = 0,
      .verbose    = self->verbose,
    };
    result = platform_exec(&opts);

    platform_temp_file_delete(&c_file);
    platform_temp_file_delete(&obj_file);
#else
    // Unix: pipe stdin to compiler
    char const        *extra[] = {"-fPIC", "-shared"};
    c_string_array     argv    = build_gcc_argv(self, extra, 2, null);

    platform_exec_opts opts    = {
         .argv       = (char const *const *)argv.v,
         .stdin_data = str_buf(&self->program),
         .stdin_len  = str_len(self->program),
         .verbose    = self->verbose,
    };
    result = platform_exec(&opts);
    str_deinit(default_allocator(), &self->program);
#endif

    hires_timer_stop(&cc_timer);
    if (self->report_stats) {
        self->stats.cc_time_ms    = hires_timer_elapsed_sec(&cc_timer) * 1000.0;
        self->stats.cc_input_size = input_size;
    }

    return result;
}

static int format_file(state *self) {
    char       *data;
    u32         size;
    char const *filename = "<stdin>";

    if (self->in_place && self->words.size <= 1) {
        fprintf(stderr, "error: cannot use --in-place with stdin\n");
        return 1;
    }

    if (self->words.size > 1) {
        filename = self->words.v[1];
        file_read(self->arena, filename, &data, &size);
    } else {
        // Read all of stdin
        u32 capacity = 64 * 1024;
        data         = alloc_malloc(self->arena, capacity);
        size         = 0;
        for (;;) {
            size_t n = fread(data + size, 1, capacity - size, stdin);
            size += (u32)n;
            if (n == 0) break;
            if (size == capacity) {
                u32   new_cap = capacity * 2;
                char *new_buf = alloc_malloc(self->arena, new_cap);
                memcpy(new_buf, data, size);
                data     = new_buf;
                capacity = new_cap;
            }
        }
    }

    str result = tl_format(self->arena, data, size, filename);

    if (self->in_place) {
        FILE *f = fopen(filename, "wb");
        if (!f) {
            fprintf(stderr, "error: could not open '%s' for writing\n", filename);
            return 1;
        }
        fwrite(str_buf(&result), 1, str_len(result), f);
        fclose(f);
    } else {
        fwrite(str_buf(&result), 1, str_len(result), stdout);
    }

    return 0;
}

static int pack_files(state *self) {
    // Validate arguments
    if (!self->out_path) {
        fprintf(stderr, "error: -o option is required for pack command\n");
        return 1;
    }

    if (self->words.size < 2) {
        fprintf(stderr, "error: pack command requires input file(s)\n");
        usage(1, self->argv0);
        return 1;
    }

    // Get input files (skip command name)
    c_string_csized input_files = {.v = self->words.v + 1, .size = self->words.size - 1};

    // Get all files in dependency order using existing infrastructure
    str_sized all_files = files_in_order(self, input_files);

    // Determine base directory from first input file
    str first_input = str_init(self->arena, input_files.v[0]);
    str first_norm  = file_path_normalize(self->arena, str_cstr(&first_input));
    str base_dir    = file_dirname(self->arena, str_cstr(&first_norm));

    if (str_is_empty(base_dir)) {
        // Use current directory
        char cwd_buf[4096];
        if (!file_current_working_directory((span){.buf = cwd_buf, .len = sizeof(cwd_buf)})) {
            fprintf(stderr, "error: failed to determine current working directory\n");
            return 1;
        }
        base_dir = str_init(self->arena, cwd_buf);
    }

    if (self->verbose) {
        fprintf(stderr, "Archive base directory: %s\n", str_cstr(&base_dir));
    }

    // Count non-stdlib files and allocate entries
    u32 user_file_count = 0;
    forall(i, all_files) {
        if (!import_resolver_is_stdlib_file(self->resolver, all_files.v[i])) {
            user_file_count++;
        }
    }

    if (user_file_count == 0) {
        fprintf(stderr, "error: no user files to pack (only standard library dependencies)\n");
        return 1;
    }

    tl_tlib_entry *entries   = alloc_malloc(self->arena, user_file_count * sizeof(tl_tlib_entry));
    u32            entry_idx = 0;

    // Process each file
    forall(i, all_files) {
        str file_path = all_files.v[i];

        // Skip standard library files
        if (import_resolver_is_stdlib_file(self->resolver, file_path)) {
            if (self->verbose) {
                fprintf(stderr, "Skipping stdlib: %s\n", str_cstr(&file_path));
            }
            continue;
        }

        // Compute relative path from base directory
        str rel_path = file_path_relative(self->arena, str_cstr(&base_dir), str_cstr(&file_path));

        if (str_is_empty(rel_path)) {
            fprintf(stderr, "error: cannot compute relative path for: %s\n", str_cstr(&file_path));
            fprintf(stderr, "       from base directory: %s\n", str_cstr(&base_dir));
            return 1;
        }

        // Validate filename for archive (no "..", no absolute paths)
        if (!tl_tlib_valid_filename(str_cstr(&rel_path), (u32)str_len(rel_path))) {
            fprintf(stderr, "error: invalid archive path: %s\n", str_cstr(&rel_path));
            fprintf(stderr, "       Archive paths must not contain '..' or be absolute.\n");
            return 1;
        }

        // Read file contents
        char *data;
        u32   size;
        file_read(self->arena, str_cstr(&file_path), &data, &size);
        if (!data) {
            fprintf(stderr, "error: failed to read file: %s\n", str_cstr(&file_path));
            return 1;
        }

        if (self->verbose) {
            fprintf(stderr, "Packing: %s (%u bytes)\n", str_cstr(&rel_path), size);
        }

        // Add to entries
        entries[entry_idx].name     = str_cstr(&rel_path);
        entries[entry_idx].name_len = (u32)str_len(rel_path);
        entries[entry_idx].data     = (byte const *)data;
        entries[entry_idx].data_len = size;
        entry_idx++;
    }

    // Write archive
    if (self->verbose) {
        fprintf(stderr, "Writing archive with %u files to: %s\n", entry_idx, self->out_path);
    }

    int result = tl_tlib_write(self->arena, self->out_path, entries, entry_idx);

    if (result == 0) {
        if (self->verbose) {
            fprintf(stderr, "Archive created successfully.\n");
        }
    }

    return result;
}

int main(int argc, char *argv[]) {

    int         result = 0;
    char        buf[256];
    span        buf_s = {.buf = buf, .len = sizeof buf};

    hires_timer timer;
    hires_timer_init(&timer);

    if (!file_current_working_directory(buf_s)) {
        fprintf(stderr, "failed to determine current working directory.\n");
        exit(1);
    }

    state self;
    state_init(&self);
    state_gather_options(&self, argc, argv);

    // Auto-define DEBUG or NDEBUG based on optimization mode
    str auto_def = str_init(self.arena, self.optimize ? "NDEBUG" : "DEBUG");
    array_push(self.defines, auto_def);

    // Populate import_defines hset from -D flags
    forall(i, self.defines) {
        str_hset_insert(&self.import_defines, self.defines.v[i]);
    }

    if (!self.no_standard_includes) {
        add_standard_include_paths(&self, buf);
    }

    get_c_compiler(&self);
    if (str_is_empty(self.cc)) {
        fprintf(stderr, "Could not locate a working C compiler. Set CC environment "
                        "variable and try again.");
        exit(1);
    }

    if (self.verbose) {
        fprintf(stderr, "Current working directory: %s\n", buf_s.buf);
        fprintf(stderr, "C compiler: %s\n", str_cstr(&self.cc));
        if (self.no_standard_includes) fprintf(stderr, "Ignoring standard include paths\n");
        import_resolver_print_paths(self.resolver);
        forall(i, self.defines) {
            fprintf(stderr, "-D %s\n", str_cstr(&self.defines.v[i]));
        }
    }

    if (self.help) usage(0, argv[0]);
    if (self.words.size == 0) usage(0, argv[0]);

    if (0 == strcmp("c", self.words.v[0])) {
        hires_timer_start(&timer);
        result = compile(&self);
    }

    else if (0 == strcmp("exe", self.words.v[0])) {
        hires_timer_start(&timer);
        if (!self.out_path) {
            fprintf(stderr, "error: -o option is missing\n");
            exit(1);
        }
        self.is_executable = 1;
        result             = compile(&self);
        if (result) goto done;
        result = compile_c(&self);
    }

    else if (0 == strcmp("fmt", self.words.v[0])) {
        result = format_file(&self);
    }

    else if (0 == strcmp("lib-emit-c", self.words.v[0])) {
        hires_timer_start(&timer);

        self.is_library = 1;
        result          = compile(&self);
        output_program(&self);
    }

    else if (0 == strcmp("lib", self.words.v[0])) {
        hires_timer_start(&timer);
        if (!self.out_path) {
            fprintf(stderr, "error: -o option is missing\n");
            exit(1);
        }
        self.is_library = 1;
        result          = compile(&self);
        if (result) goto done;
        result = compile_c_obj(&self);
    }

    else if (0 == strcmp("pack", self.words.v[0])) {
        result = pack_files(&self);
    }

done:
    hires_timer_stop(&timer);

    if (self.report_stats && !result) {
        print_stats_header();
        print_stats_row("Parsing", self.stats.parse_time_ms, self.stats.parse_peak_mem,
                        self.stats.parse_final_mem);
        print_stats_row("Type Inference", self.stats.infer_time_ms, self.stats.infer_peak_mem,
                        self.stats.infer_final_mem);
        print_stats_row("Transpilation", self.stats.transpile_time_ms, self.stats.transpile_peak_mem,
                        self.stats.transpile_final_mem);

        double total_ms =
          self.stats.parse_time_ms + self.stats.infer_time_ms + self.stats.transpile_time_ms;
        size_t total_peak =
          self.stats.parse_peak_mem + self.stats.infer_peak_mem + self.stats.transpile_peak_mem;

        // C compilation phase (only for exe/lib commands)
        if (self.is_executable || self.is_library) {
            print_stats_row_no_mem("C Compilation", self.stats.cc_time_ms, self.stats.cc_input_size);
            total_ms += self.stats.cc_time_ms;
        }

        print_stats_footer(total_ms, total_peak);
    }

    if (self.report_time) {
        double elapsed = hires_timer_elapsed_sec(&timer);
        double ms      = elapsed * 1000;
        fprintf(stderr, "Elapsed time: %0.6fms\n", ms);
    }

    state_deinit(&self);
    return result;
}
