#include "v2_transpile.h"

#include "alloc.h"
#include "str.h"
#include "v2_type.h"

#define TRANSPILE_ARENA_SIZE     32 * 1024
#define TRANSPILE_TRANSIENT_SIZE 32 * 1024
#define TRANSPILE_BUILD_SIZE     32 * 1024

struct transpile {
    allocator   *parent;
    allocator   *arena;
    allocator   *transient;

    tl_type_env *env;
    hashmap     *toplevels; // str => ast_node*

    str_build    build;

    int          verbose;
};

static void generate_prototypes(transpile *self);

static void cat(transpile *, str);
static void cat_nl(transpile *);
static void cat_sp(transpile *);
static void cat_double_slash(transpile *);
static void cat_open_round(transpile *);
static void cat_close_round(transpile *);
static void cat_semicolon(transpile *);
static void catln(transpile *, str);
static void cat_comment(transpile *, str);
static void cat_commentln(transpile *, str);

static str  mangle_fun(transpile *, str); // allocates transient
static int  is_intrinsic(str);
static int  should_generate(str, tl_type_v2 const *);
static str  type_to_c(tl_type_v2 const *);
static str  arrow_rhs_to_c(tl_type_v2 const *);
static str  arrow_to_c_params(transpile *, tl_type_v2 const *); // allocates transient

//

static void generate_prototypes(transpile *self) {
    forall(i, self->env->names) {
        str         name = self->env->names.v[i];
        tl_type_v2 *type = &self->env->types.v[i];

        // skip non-arrow types, main, any generic types, intrinsics
        if (!should_generate(name, type)) continue;

        str ret = arrow_rhs_to_c(type);
        cat_double_slash(self);
        cat(self, ret);
        cat_sp(self);
        cat(self, mangle_fun(self, name));
        cat_open_round(self);
        cat(self, arrow_to_c_params(self, type));
        cat_close_round(self);
        cat_semicolon(self);

        cat_nl(self);
    }
}

int transpile_compile(transpile *self, str_build *out_build) {

    self->build = str_build_init(self->parent, TRANSPILE_BUILD_SIZE);

    generate_prototypes(self);

    cat_comment(self, S("hello, world"));

    if (out_build) {
        *out_build = self->build;
    }
    return 0;
}

//

transpile *transpile_create(allocator *alloc, transpile_opts const *opts) {
    transpile *self = new (alloc, transpile);

    self->parent    = alloc;
    self->arena     = arena_create(alloc, TRANSPILE_ARENA_SIZE);
    self->transient = arena_create(alloc, TRANSPILE_TRANSIENT_SIZE);

    self->env       = opts->infer_result.env;
    self->toplevels = opts->infer_result.toplevels;
    self->verbose   = !!opts->verbose;

    return self;
}

void transpile_destroy(allocator *alloc, transpile **p) {
    if (!p || !*p) return;

    arena_destroy(alloc, &(*p)->transient);
    arena_destroy(alloc, &(*p)->arena);
    alloc_free(alloc, *p);
    *p = null;
}

void transpile_set_verbose(transpile *self, int val) {
    self->verbose = val;
}

//

static void cat(transpile *self, str s) {
    str_build_cat(&self->build, s);
}
static void cat_nl(transpile *self) {
    cat(self, S("\n"));
}
static void cat_sp(transpile *self) {
    cat(self, S(" "));
}
static void cat_double_slash(transpile *self) {
    cat(self, S("// "));
}
static void cat_open_round(transpile *self) {
    cat(self, S("("));
}
static void cat_close_round(transpile *self) {
    cat(self, S(")"));
}
static void cat_semicolon(transpile *self) {
    cat(self, S(";"));
}
static void catln(transpile *self, str s) {
    cat(self, s);
    cat_nl(self);
}
static void cat_comment(transpile *self, str s) {
    cat(self, S("/* "));
    cat(self, s);
    cat(self, S(" */"));
}
static void cat_commentln(transpile *self, str s) {
    cat_comment(self, s);
    cat_nl(self);
}

//

static str mangle_fun(transpile *self, str s) {
    str_build b = str_build_init(self->transient, str_len(s) + 8);
    str_build_cat(&b, S("_tl_fun_"));
    str_build_cat(&b, s);

    return str_build_finish(&b);
}

static int is_intrinsic(str s) {
    return 0 == str_cmp_nc(s, "_tl_", 4);
}

static int should_generate(str name, tl_type_v2 const *type) {
    // return 0 if this function should not be generated by transpile
    // during its processing of functions in the environment.
    if (!tl_type_v2_is_arrow(type)) return 0;
    if (tl_type_v2_is_scheme(type)) return 0;
    if (str_eq(name, S("main"))) return 0;
    if (is_intrinsic(name)) return 0;
    return 1;
}

static str type_to_c(tl_type_v2 const *type) {
    if (tl_type_v2_is_scheme(type)) fatal("type scheme");
    tl_monotype const *mono = &type->mono;
    if (tl_cons == mono->tag) {
        if (str_eq(S("Int"), mono->cons.name)) {
            return S("int64_t");
        } else if (str_eq(S("Float"), mono->cons.name)) {
            return S("double");
        } else if (str_eq(S("String"), mono->cons.name)) {
            return S("char const*");
        } else fatal("unknown type constructor");
    } else if (tl_nil == mono->tag) {
        return S("void");
    } else fatal("not yet implemented");
}
static str type_to_c_mono(tl_monotype const *type) {
    tl_type_v2 t = tl_type_init_mono(*type);
    return type_to_c(&t);
}

static str arrow_rhs_to_c(tl_type_v2 const *type) {
    if (tl_type_v2_is_scheme(type)) fatal("type scheme");
    tl_monotype const *right = tl_type_v2_arrow_rightmost(&type->mono);
    return type_to_c_mono(right);
}

// tl_monotype const     *tl_type_v2_arrow_head(tl_monotype const *);
// tl_monotype const     *tl_type_v2_arrow_next(tl_monotype const *);

static str arrow_to_c_params(transpile *self, tl_type_v2 const *type) {
    if (tl_type_v2_is_scheme(type)) fatal("type scheme");

    str_build          b    = str_build_init(self->transient, 64);
    tl_monotype const *args = tl_type_v2_arrow_head(&type->mono);
    if (!tl_monotype_is_nil(args)) {
        int done = 0;
        while (!done) {
            str_build_cat(&b, type_to_c_mono(args));
            tl_monotype const *next = tl_type_v2_arrow_next(args);
            if (next) {
                str_build_cat(&b, S(", "));
                args = next;
            } else done = 1;
        }
    }

    return str_build_finish(&b);
}
