#ifndef TESS_AST_H
#define TESS_AST_H

#include "alloc.h"
#include "array.h"
#include "ast_tags.h"
#include "error.h"
#include "mos_string.h"
#include "nodiscard.h"
#include "type.h"

typedef struct ast_node {
    union {
        struct ast_symbol {
            string_t         name;
            string_t         original; // set by syntax_rename_variable
            struct ast_node *annotation;
        } symbol;

        struct ast_bool {
            bool val;
        } bool_;

        struct ast_i64 {
            i64 val;
        } i64;

        struct ast_u64 {
            u64 val;
        } u64;

        struct ast_f64 {
            f64 val;
        } f64;

        struct ast_assignment {
            struct ast_node *name;
            struct ast_node *value;
        } assignment;

        struct ast_array {
            // all variants with arrays must use this layout
            struct ast_node **nodes;
            u8                n;
        } array;

        struct ast_begin_end {
            struct ast_node **expressions;
            u8                n_expressions;
        } begin_end;

        struct ast_lambda_function {
            struct ast_node **parameters;
            u8                n_parameters;
            struct ast_node  *body;
            // node type is arrow
        } lambda_function;

        struct ast_function_declaration {
            struct ast_node **parameters;
            u8                n_parameters;
            struct ast_node  *name;
        } function_declaration;

        struct ast_lambda_declaration {
            struct ast_node **parameters;
            u8                n_parameters;
        } lambda_declaration;

        struct ast_let {
            struct ast_node **parameters;
            u8                n_parameters;
            u8                flags;
            struct string     name;
            struct ast_node  *body;
            tl_type          *arrow;            // because the node type itself is nil
            struct string     specialized_name; // set during function specialisation
        } let;

        struct ast_lambda_application {
            struct ast_node **arguments;
            u8                n_arguments;
            struct ast_node  *lambda;
        } lambda_application;

        struct ast_named_application {
            struct ast_node **arguments;
            u8                n_arguments;
            struct string     name;
            struct ast_node  *specialized;
        } named_application;

        struct ast_labelled_tuple {
            struct ast_node **assignments;
            u8                n_assignments;
        } labelled_tuple;

        struct ast_tuple {
            struct ast_node **elements;
            u8                n_elements;
            u8                flags;
        } tuple;

        struct ast_user_type {
            struct ast_node **fields;
            u8                n_fields;
            struct ast_node  *name;
        } user_type; // a type literal, generated by compiler as body of constructor

        // below have no array

        struct ast_if_then_else {
            struct ast_node *condition;
            struct ast_node *yes;
            struct ast_node *no;
        } if_then_else;

        struct ast_infix {
            ast_operator     op;
            struct ast_node *left;
            struct ast_node *right;
        } infix;

        struct ast_let_in {
            struct ast_node *name;
            struct ast_node *value;
            struct ast_node *body;
        } let_in;

        struct ast_let_match_in {
            struct ast_node *lt; // labelled_tuple
            struct ast_node *value;
            struct ast_node *body;
        } let_match_in;

        struct ast_user_type_get {
            struct ast_node *struct_name;
            struct ast_node *field_name;
        } user_type_get;

        struct ast_user_type_set {
            struct ast_node *struct_name;
            struct ast_node *field_name;
            struct ast_node *value;
        } user_type_set;

        struct ast_user_type_def {
            struct ast_node  *name;
            struct ast_node **field_annotations;
            struct ast_node **field_names;
            tl_type         **field_types;
            u8                n_fields;
        } user_type_def;
    };

    tl_type          *type;
    ast_tag           tag;
    enum tl_error_tag error;
} ast_node;

typedef struct {
    array_header;
    ast_node **v;
} ast_node_array;

typedef struct {
    array_slice;
    ast_node **v;
} ast_node_slice;

typedef struct {
    array_sized;
    ast_node **v;
} ast_node_sized;

#define AST_LET_FLAG_SPECIALIZED BIT(0)
#define AST_LET_FLAG_TUPLE_CONS  BIT(1)

#define AST_TUPLE_FLAG_INIT      BIT(0)

// -- iterator functions --

typedef void (*ast_op_fun)(void *, ast_node *);
typedef void (*ast_op_cfun)(void *, ast_node const *);

// -- variant accessors --

struct ast_assignment           *ast_node_assignment(ast_node *);
struct ast_bool                 *ast_node_bool(ast_node *);
struct ast_i64                  *ast_node_i64(ast_node *);
struct ast_u64                  *ast_node_u64(ast_node *);
struct ast_f64                  *ast_node_f64(ast_node *);
struct ast_array                *ast_node_arr(ast_node *);
struct ast_infix                *ast_node_infix(ast_node *);
struct ast_lambda_function      *ast_node_lf(ast_node *);
struct ast_let_in               *ast_node_let_in(ast_node *);
struct ast_let_match_in         *ast_node_let_match_in(ast_node *);
struct ast_function_declaration *ast_node_fd(ast_node *);
struct ast_lambda_declaration   *ast_node_let_ld(ast_node *);
struct ast_let                  *ast_node_let(ast_node *);
struct ast_if_then_else         *ast_node_ifthen(ast_node *);
struct ast_lambda_application   *ast_node_lambda(ast_node *);
struct ast_named_application    *ast_node_named(ast_node *);
struct ast_labelled_tuple       *ast_node_lt(ast_node *);
struct ast_symbol               *ast_node_sym(ast_node *);
struct ast_tuple                *ast_node_tuple(ast_node *);
struct ast_begin_end            *ast_node_begin_end(ast_node *);
struct ast_user_type            *ast_node_ut(ast_node *);
struct ast_user_type_get        *ast_node_utg(ast_node *);
struct ast_user_type_set        *ast_node_uts(ast_node *);
struct ast_user_type_def        *ast_node_utd(ast_node *);

// -- ast_node --

nodiscard ast_node *ast_node_create(allocator *, ast_tag) mallocfun;
nodiscard ast_node *ast_node_create_sym(allocator *, char const *);
nodiscard ast_node *ast_node_clone(allocator *, ast_node const *) mallocfun;
// void                ast_node_init(allocator *, ast_node *, ast_tag);
// void                ast_node_deinit(allocator *, ast_node *);
// void        ast_node_replace(allocator *, ast_node *, ast_tag);
void        ast_node_move(ast_node *dst, ast_node *src);

char const *ast_node_name_string(ast_node const *);
int         ast_node_name_strcmp(ast_node const *, char const *);

// -- traversal --

typedef void (*ast_node_each_node_fun)(void *ctx, ast_node *);
typedef void (*ast_node_each_type_fun)(void *ctx, tl_type *);

void ast_node_each_node(void *, ast_node_each_node_fun, ast_node *);
void ast_node_each_type(void *, ast_node_each_type_fun, ast_node *);

// -- utilities --

char           *ast_node_to_string(allocator *alloc, ast_node const *node);
char           *ast_node_to_string_for_error(allocator *, ast_node const *);

char const     *ast_tag_to_string(ast_tag);
int             string_to_ast_operator(char const *, ast_operator *);

c_string_csized ast_nodes_get_names(allocator *, ast_node_slice);

void            ast_node_dfs(void *, ast_node *, ast_op_fun);
void            ast_node_cdfs(void *, ast_node const *, ast_op_cfun);

bool            ast_node_is_specialized(ast_node const *);
bool            ast_node_is_tuple_constructor(ast_node const *);
void            ast_node_set_is_specialized(ast_node *);
void            ast_node_set_is_tuple_constructor(ast_node *);

#endif
