(* all concatenations with may include arbitrary separating whitespace *)
program       = { toplevel } ;
toplevel      = assignment | defun | defstruct ;

(* note: an assignment is not an expression *)
assignment    = ident "=" expression ;

ident         = ident_start { alphanumeric } ;
ident_start   = alphabetic | "_" ;
alphanumeric  = alphabetic | numeric | "_" ;
alphabetic    = "a" .. "z" | "A" .. "Z"  ;
numeric       = "0" .. "9" ;

value         = literal | ident | funcall ;
literal       = integer | float | string ;
funcall       = ident "(" [ argument_list ] ")" ;
argument_list = expression { "," expression } ;

integer       = [ "+" | "-" ] numeric { numeric } ;
float         = integer "." numeric { numeric } [ ( "e" | "E" ) integer ] ;
string        = '"' { ? any character except quote ? } '"' ;

defun         = ident "(" [ param_list ] ")" fun_body;
param_list    = param { "," param } ;
param         = ident [ ":" type ] ;
type          = ident { " " ident } ;
fun_body      = "{" { statement | expression } "}" ;
statement     = assignment | for_stmt | return_stmt ;

expression    = base_expr { binary_op base_expr } ;
base_expr     = [ unary_op ] ( value | "(" expression ")" | if_expr | cond_expr );
if_expr       = "if" expression "{" body_expr "}" { "else" if_expr } [ else_case ]  ;
else_case     = "else" "{" body_expr "}" ;
body_expr     = statement | break_stmt ;

cond_expr     = "cond" "{" { cond_arm } cond_else "}" ;
cond_arm      = "(" expression ")" "{" { body_expr } "}" ;
cond_else     = "()" "{" { body_expr } "}" ;

return_stmt   = "return" expression ;

(* break: similar to return_stmt but at the block level: sets the value of the block and exits *)
break_stmt    = "break" expression ;

for_stmt      = "for" "(" [ for_assign ] ";" [ expression ] ";" [ for_update ] ")" "{" { for_body } "}";
for_assign    = assignment { "," assignment } ;
for_body      = body_expr | continue_stmt ;
for_update    = for_upd_item { "," for_upd_item } ;
for_upd_item  = assignment | expression ;
continue_stmt = "continue" ;

binary_op     = "+" | "-" | "*" | "/" | rel_op | logical_op ;
rel_op        = "==" | "!=" | "<=" | "<" | ">=" | ">" ;
logical_op    = "&&" | "||" ;
unary_op      = "-" | "!" ;

defstruct     = "struct" type "{" { field_list }  "}" ;
field_list    = field { "," field } ;
field         = ident ":" type ;

(*

Notes:

- An expression generates a value. A statement does not generate a value (or generates a nil value for type checking purposes).
- An assignment is not an expression; it is a statement with nil value. This prevents errors like "if (a = 5)" when
  "if (a == 5)" was intended.

*)
